# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gl-89O3IexgWJThblfHD_THnIhMeC0Ee
"""

# Oppo/tests/__init__.py

"""
This file marks the 'tests' directory as a Python package.
It can also be used for test-wide fixtures or configuration if needed.
"""

import sys
import os

# Add the project root directory to the Python path
# This allows tests to import modules from the 'oppo' package
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

print(f"Initializing Oppo tests package. Project root added to sys.path: {project_root}")

# You could define test-wide fixtures here using pytest_plugins,
# or configure logging specifically for tests.
# Example:
# pytest_plugins = ['tests.fixtures.database_fixtures']