# -*- coding: utf-8 -*-
"""test_a2a_host

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TE9arIpzWzfdvzzfV9CtpGaWbRfXo54S
"""

# Oppo/tests/test_a2a_host.py

"""
Tests for the A2A Host FastAPI application (server.py).

Uses pytest, pytest-asyncio, and mocks dependencies like the
analysis engine components, MCP client, and authentication.
"""

import pytest
import pytest_asyncio
from unittest.mock import AsyncMock, MagicMock, patch
from fastapi.testclient import TestClient
from datetime import datetime
import uuid
import json

# Attempt to import the A2A Host app and dependencies
try:
    # Assume the main app instance is 'app' in oppo.a2a_host.server
    from oppo.a2a_host.server import app as a2a_app
    # Import auth dependency function if needed for mocking
    # from oppo.a2a_host.auth import get_current_active_user
    # Import models used in requests/responses
    from oppo.database.data_models import SocialPost, Candidate # Assuming these are used
    from oppo.a2a_host.a2a_protocol import A2ARequest, A2AResponse, MessageType
    # Import components to be mocked
    from oppo.analysis.llm_interface import LLMInterface # If directly used, else mock analyzers
    from oppo.analysis.contradiction_detector import ContradictionDetector
    from oppo.analysis.disinformation_analyzer import DisinformationAnalyzer
    from oppo.analysis.fact_checker import FactChecker
    from oppo.analysis.evasion_detector import EvasionDetector
    from oppo.analysis.decision_engine import DecisionEngine
    from oppo.analysis.report_generator import ReportGenerator
    # Import MCP client mock (or create a new one) if MCP is called directly
    # from oppo.database.modern_context_protocol_client import MCPClient # Assuming a client class exists
except ImportError as e:
    pytest.skip(f"Skipping A2A Host tests due to import error: {e}", allow_module_level=True)

# --- Mocks ---

# Mock for the MCP Client (if the A2A host uses a dedicated client class)
# If it uses 'requests' or 'httpx' directly, mock those instead.
@pytest.fixture(scope="module")
def mock_mcp_client():
    """Fixture for a mocked MCP client."""
    mock = MagicMock() # Replace with spec if you have an MCPClient class
    mock.store_node = AsyncMock()
    mock.update_node = AsyncMock()
    mock.link_post_to_candidate = AsyncMock()
    mock.get_candidate_context = AsyncMock()
    # Add other methods called by A2A Host from MCP
    return mock

# Mocks for Analysis Components
@pytest.fixture
def mock_contradiction_detector():
    mock = MagicMock(spec=ContradictionDetector)
    mock.analyze = AsyncMock(return_value=(0.1, "Looks consistent.")) # score, explanation
    return mock

@pytest.fixture
def mock_disinformation_analyzer():
    mock = MagicMock(spec=DisinformationAnalyzer)
    mock.analyze = AsyncMock(return_value=(0.2, "Low risk of disinformation."))
    return mock

@pytest.fixture
def mock_fact_checker():
    mock = MagicMock(spec=FactChecker)
    mock.analyze = AsyncMock(return_value=(0.8, "Claim appears mostly factual based on source X.")) # score, explanation
    return mock

@pytest.fixture
def mock_evasion_detector():
    mock = MagicMock(spec=EvasionDetector)
    mock.analyze = AsyncMock(return_value=(0.05, "Direct language used."))
    return mock

@pytest.fixture
def mock_decision_engine():
    mock = MagicMock(spec=DecisionEngine)
    # Simulate calculate_scores returning final scores and trigger decision
    mock.calculate_scores = MagicMock(return_value=(0.3, True)) # overall_score, should_distribute
    return mock

@pytest.fixture
def mock_report_generator():
    mock = MagicMock(spec=ReportGenerator)
    mock.generate_report = AsyncMock(return_value={"summary": "Test report summary.", "details": {}})
    return mock

# Mock for Authentication (Example)
# This depends heavily on your actual auth implementation (e.g., JWT, OAuth2)
@pytest.fixture
def mock_auth_dependency():
    """Fixture to mock the authentication dependency."""
    # Example: Mocking a function that verifies a token and returns a user object/ID
    # async def fake_get_current_active_user():
    #     return {"username": "testuser", "scopes": ["opposition:read", "opposition:write"]}
    # return fake_get_current_active_user
    # If using FastAPI's dependency overrides, you might not need a separate fixture
    # if you override directly in the client fixture.
    pass # Placeholder


# --- Fixtures ---

@pytest_asyncio.fixture
async def client(
    mock_mcp_client, # Assuming direct MCP client usage needs mocking
    mock_contradiction_detector,
    mock_disinformation_analyzer,
    mock_fact_checker,
    mock_evasion_detector,
    mock_decision_engine,
    mock_report_generator,
    # mock_auth_dependency # Include if needed
):
    """Fixture to create a TestClient for the A2A Host FastAPI app with mocked dependencies."""

    # --- Dependency Overrides ---
    # Override dependencies used within the A2A Host application routes/logic
    # Adjust these based on how dependencies are injected (e.g., Depends(...))

    dependency_overrides = {}

    # Example: Mocking analysis components if they are injected via Depends
    # This requires knowing the exact dependency functions used in server.py
    # dependency_overrides[get_contradiction_detector] = lambda: mock_contradiction_detector
    # dependency_overrides[get_disinformation_analyzer] = lambda: mock_disinformation_analyzer
    # ... and so on for other analyzers and the decision engine ...
    # dependency_overrides[get_report_generator] = lambda: mock_report_generator

    # Example: Mocking the MCP client if injected
    # dependency_overrides[get_mcp_client] = lambda: mock_mcp_client

    # Example: Mocking authentication
    # dependency_overrides[get_current_active_user] = mock_auth_dependency

    # --- Patching ---
    # Alternatively, use patching if components are instantiated directly within routes/functions
    # (Less ideal than dependency injection for testability)

    patches = []
    # Patch the constructors or methods of the analysis components
    patches.append(patch('oppo.a2a_host.routers.opposition.ContradictionDetector', return_value=mock_contradiction_detector))
    patches.append(patch('oppo.a2a_host.routers.opposition.DisinformationAnalyzer', return_value=mock_disinformation_analyzer))
    patches.append(patch('oppo.a2a_host.routers.opposition.FactChecker', return_value=mock_fact_checker))
    patches.append(patch('oppo.a2a_host.routers.opposition.EvasionDetector', return_value=mock_evasion_detector))
    patches.append(patch('oppo.a2a_host.routers.opposition.DecisionEngine', return_value=mock_decision_engine))
    patches.append(patch('oppo.a2a_host.routers.opposition.ReportGenerator', return_value=mock_report_generator))

    # Patch MCP client interactions if not done via dependency override
    # Example assumes MCP calls happen within the opposition router
    # Adjust the target path based on your actual code structure
    # patches.append(patch('oppo.a2a_host.routers.opposition.mcp_client', mock_mcp_client)) # If mcp_client is an imported object
    # Or patch specific functions if requests/httpx are used directly
    patches.append(patch('oppo.a2a_host.routers.opposition.call_mcp', mock_mcp_client)) # If MCP calls are wrapped in a function


    # Apply patches
    for p in patches:
        p.start()

    # Apply dependency overrides to the app
    a2a_app.dependency_overrides = dependency_overrides

    # Create the TestClient
    with TestClient(a2a_app) as test_client:
        yield test_client

    # Stop patches and clear overrides
    for p in patches:
        p.stop()
    a2a_app.dependency_overrides = {}


# --- Test Cases ---

# Note: Authentication headers/tokens might be needed for most tests below.
# Add headers={'Authorization': 'Bearer your_test_token'} if required.

@pytest.mark.asyncio
async def test_a2a_host_health_check(client):
    """Test the root/health endpoint of the A2A host."""
    # Assuming you have a root endpoint for basic checks
    response = client.get("/")
    # Check status code and response based on your root endpoint implementation
    assert response.status_code == 200
    assert "Oppo A2A Host" in response.text # Example check

# --- Ingestion Endpoint Tests ---

@pytest.mark.asyncio
async def test_ingest_social_post_success(client, mock_mcp_client, mock_decision_engine):
    """Test successful ingestion and analysis trigger via POST /ingest/social."""
    post_id = str(uuid.uuid4())
    candidate_id = str(uuid.uuid4())
    now = datetime.utcnow()
    ingest_payload = {
        "platform": "YouTube",
        "platform_post_id": "vid123",
        "candidate_id": candidate_id, # This should likely be resolved from channel_id
        "channel_id": "UCTestChannel",
        "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ/vid123",
        "content": "Test video content for analysis.",
        "published_at": now.isoformat(),
        "raw_data": {"title": "Test Video"}
    }

    # Mock MCP responses needed during ingestion
    # 1. Store the raw SocialPost node
    mock_mcp_client.store_node.return_value = {"success": True, "node_id": post_id}
    # 2. Link post to candidate (assuming candidate exists)
    mock_mcp_client.link_post_to_candidate.return_value = {"message": "Relationship created"}
    # 3. Get context for analysis
    mock_mcp_client.get_candidate_context.return_value = {"success": True, "posts": []} # No previous posts for simplicity
    # 4. Update node with analysis scores
    mock_mcp_client.update_node.return_value = {"success": True, "node_id": post_id}

    # Mock analysis components are already set up by fixtures to return default values

    # Mock decision engine score calculation and distribution decision
    mock_decision_engine.calculate_scores.return_value = (0.4, True) # score, should_distribute=True

    # TODO: Mock A2A distribution logic if it's called synchronously
    # Example: patch('oppo.a2a_host.distribution.send_alert', AsyncMock())

    # Assuming the endpoint takes the SocialPost model directly or similar structure
    # Adjust the endpoint path if needed
    response = client.post("/api/v1/ingest/social", json=ingest_payload) # Add auth headers if needed

    assert response.status_code == 202 # Accepted (if analysis is async) or 201/200

    # Assert MCP calls were made
    # 1. Store initial post
    assert mock_mcp_client.store_node.call_count == 1
    store_call_args = mock_mcp_client.store_node.call_args[0][0] # Get the MCPStoreNodeRequest
    assert store_call_args.node_label == "SocialPost"
    assert store_call_args.properties["platform_post_id"] == "vid123"

    # 2. Link post (adjust if candidate lookup happens first)
    # assert mock_mcp_client.link_post_to_candidate.call_count == 1
    # link_call_args = mock_mcp_client.link_post_to_candidate.call_args[0]
    # assert link_call_args[0] == post_id # post_id
    # assert link_call_args[1] == candidate_id # candidate_id

    # Assert analysis components were called (if sync)
    # mock_contradiction_detector.analyze.assert_called_once()
    # mock_disinformation_analyzer.analyze.assert_called_once()
    # ... etc.

    # Assert decision engine was called
    # mock_decision_engine.calculate_scores.assert_called_once()

    # Assert MCP update call with scores was made
    # assert mock_mcp_client.update_node.call_count == 1
    # update_call_args = mock_mcp_client.update_node.call_args[0][0] # MCPUpdateNodeRequest
    # assert update_call_args.node_id == post_id
    # assert "contradiction_score" in update_call_args.properties
    # assert "overall_significance_score" in update_call_args.properties

    # Assert distribution was triggered (if should_distribute was True)
    # mock_send_alert.assert_called_once()


# --- A2A Protocol Endpoint Tests ---

@pytest.mark.asyncio
async def test_a2a_report_request(client, mock_report_generator, mock_mcp_client):
    """Test a valid A2A request for a report."""
    request_payload = {
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.utcnow().isoformat(),
        "sender_id": "agent-campaign-1",
        "recipient_id": "oppo-host-main",
        "message_type": MessageType.REPORT_REQUEST.value,
        "payload": {
            "candidate_id": "candidate-abc", # ID or other criteria
            "topic": "Recent statements on economy",
            "timeframe_start": (datetime.utcnow() - timedelta(days=7)).isoformat(),
            "timeframe_end": datetime.utcnow().isoformat(),
        }
    }
    a2a_request = A2ARequest(**request_payload)

    # Mock MCP calls needed by report generator
    mock_mcp_client.get_candidate_context.return_value = {"success": True, "posts": []} # Example
    # Mock other potential MCP calls for candidate details, etc.

    # Mock report generator response
    mock_report_generator.generate_report.return_value = {
        "report_id": str(uuid.uuid4()),
        "candidate_id": "candidate-abc",
        "summary": "Summary of recent economic statements.",
        "findings": [],
        "generated_at": datetime.utcnow().isoformat()
    }

    # Assuming endpoint /api/v1/a2a/receive or similar
    response = client.post("/api/v1/a2a/receive", json=a2a_request.dict()) # Add auth

    assert response.status_code == 200
    response_data = response.json()
    a2a_response = A2AResponse(**response_data)

    assert a2a_response.message_type == MessageType.REPORT_RESPONSE
    assert a2a_response.in_reply_to == a2a_request.message_id
    assert a2a_response.sender_id == "oppo-host-main" # Should be the host
    assert a2a_response.recipient_id == a2a_request.sender_id
    assert a2a_response.payload["summary"] == "Summary of recent economic statements."

    # Verify report generator was called with correct parameters
    mock_report_generator.generate_report.assert_called_once()
    # Check arguments passed to generate_report based on its signature

@pytest.mark.asyncio
async def test_a2a_invalid_message_type(client):
    """Test A2A request with an unsupported message type."""
    request_payload = {
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.utcnow().isoformat(),
        "sender_id": "agent-x",
        "recipient_id": "oppo-host-main",
        "message_type": "INVALID_TYPE", # Not a valid MessageType enum value
        "payload": {}
    }

    response = client.post("/api/v1/a2a/receive", json=request_payload) # Add auth

    assert response.status_code == 400 # Bad Request or 422 Unprocessable Entity
    response_data = response.json()
    # Check for appropriate error message, depends on FastAPI validation
    assert "value is not a valid enumeration member" in str(response_data).lower() or \
           "invalid message type" in str(response_data).lower()


# Add more tests for:
# - Other A2A message types (ALERT, ACK, ERROR)
# - Authentication failures
# - Error handling within ingestion (e.g., MCP failures, analysis errors)
# - Specific router logic in opposition.py
# - Input validation errors (e.g., invalid SocialPost data)