# -*- coding: utf-8 -*-
"""test_database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ju1UTBtoYPI3f31f_z0kLm5benAqfTuS
"""

# Oppo/tests/test_database.py

"""
Tests for the database interaction layer, primarily focusing on the
Modern Context Protocol (MCP) FastAPI server endpoints.

Uses pytest, pytest-asyncio, and mocks the Neo4jClient dependency.
"""

import pytest
import pytest_asyncio
from unittest.mock import AsyncMock, MagicMock, patch
from fastapi.testclient import TestClient
from datetime import datetime
import uuid

# Import the FastAPI app and data models from the database module
# Assuming the app instance is named 'app' in modern_context_protocol.py
# Adjust the import path if your project structure is different
try:
    from oppo.database.modern_context_protocol import app as mcp_app, get_db as mcp_get_db, INTERNAL_SERVICE_API_KEY
    from oppo.database.data_models import (
        Candidate, SocialPost, ListenerState,
        MCPStoreNodeRequest, MCPUpdateNodeRequest, MCPGetNodeRequest,
        MCPGetListenerStateRequest, MCPSetListenerStateRequest,
        MCPGetCandidateContextRequest
    )
    from oppo.database.neo4j_client import Neo4jClient
except ImportError as e:
     pytest.skip(f"Skipping database tests due to import error: {e}", allow_module_level=True)


# --- Fixtures ---

@pytest.fixture(scope="module")
def mock_neo4j_client():
    """Fixture to create a mock Neo4jClient."""
    mock_client = MagicMock(spec=Neo4jClient)
    # Mock the core query execution method
    mock_client.execute_query = AsyncMock()
    # Mock other methods if directly called by MCP (though execute_query is primary)
    mock_client.close = MagicMock()
    return mock_client

@pytest.fixture(scope="module")
def test_api_key():
    """Fixture to provide the test API key."""
    # In a real scenario, load this securely or use a dedicated test key
    test_key = "test_internal_api_key_12345"
    # Patch the environment variable ONLY for the test session if it's not set,
    # otherwise use the one potentially set for the test environment.
    original_key = INTERNAL_SERVICE_API_KEY
    if not original_key:
        os.environ["INTERNAL_SERVICE_API_KEY"] = test_key
        # Update the module variable after patching environ
        from oppo.database import modern_context_protocol
        modern_context_protocol.INTERNAL_SERVICE_API_KEY = test_key
        yield test_key
        del os.environ["INTERNAL_SERVICE_API_KEY"]
        modern_context_protocol.INTERNAL_SERVICE_API_KEY = original_key # Restore
    else:
        # If the key was already set (e.g., by test env setup), use that
        yield original_key


@pytest.fixture(scope="module")
def client(mock_neo4j_client, test_api_key):
    """Fixture to create a TestClient for the MCP FastAPI app with mocked DB."""

    # Define override function for the get_db dependency
    def override_get_db():
        try:
            yield mock_neo4j_client
        finally:
            # No cleanup needed for mock, real client cleanup is handled by app shutdown
            pass

    # Apply the dependency override
    mcp_app.dependency_overrides[mcp_get_db] = override_get_db

    # Create the TestClient instance
    with TestClient(mcp_app) as test_client:
        yield test_client

    # Clean up the dependency override after tests
    mcp_app.dependency_overrides = {}


# --- Test Cases ---

@pytest.mark.asyncio
async def test_health_check(client):
    """Test the /health endpoint."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}

@pytest.mark.asyncio
async def test_store_node_candidate_merge_id(client, mock_neo4j_client, test_api_key):
    """Test POST /nodes/store for merging a Candidate by ID."""
    candidate_id = str(uuid.uuid4())
    candidate_data = {
        "id": candidate_id,
        "name": "Test Candidate",
        "party": "Independent",
        "state": "TS",
        # Add other required fields if necessary
    }
    request_payload = {
        "node_label": "Candidate",
        "properties": candidate_data,
        # unique_field is omitted, merge should happen on 'id'
    }

    # Configure mock response from Neo4jClient
    mock_neo4j_client.execute_query.return_value = [{"node_id": candidate_id}]

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/nodes/store", json=request_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    assert response_data["node_id"] == candidate_id
    assert "stored successfully" in response_data["message"]

    # Verify execute_query was called correctly
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert "MERGE (n:Candidate { id: $node_id })" in call_args[0] # Check query structure
    assert call_kwargs["parameters"]["props"]["name"] == "Test Candidate"
    assert call_kwargs["parameters"]["node_id"] == candidate_id
    assert call_kwargs["write"] is True

@pytest.mark.asyncio
async def test_store_node_socialpost_create(client, mock_neo4j_client, test_api_key):
    """Test POST /nodes/store for creating a new SocialPost (no unique field/ID)."""
    post_id = str(uuid.uuid4())
    post_data = {
        # "id": post_id, # ID is NOT provided for CREATE test
        "platform": "TestPlatform",
        "platform_post_id": "test-post-123",
        "candidate_id": str(uuid.uuid4()),
        "channel_id": "test-channel-456",
        "content": "This is test content.",
        "published_at": datetime.utcnow().isoformat(),
    }
    request_payload = {
        "node_label": "SocialPost",
        "properties": post_data,
    }

    # Mock execute_query to return the generated ID
    # Simulate Neo4j returning the ID of the created node
    mock_neo4j_client.execute_query.reset_mock() # Reset from previous test
    mock_neo4j_client.execute_query.return_value = [{"node_id": post_id}] # Simulate ID return

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/nodes/store", json=request_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    # The ID returned should be the one Neo4j generated (mocked here)
    assert response_data["node_id"] == post_id
    assert "stored successfully" in response_data["message"]

    # Verify execute_query was called with CREATE
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert "CREATE (n:SocialPost)" in call_args[0] # Check query structure
    assert call_kwargs["parameters"]["props"]["platform_post_id"] == "test-post-123"
    assert "id" not in call_kwargs["parameters"]["props"] # Ensure ID wasn't in the props sent to DB
    assert call_kwargs["write"] is True


@pytest.mark.asyncio
async def test_update_node_success(client, mock_neo4j_client, test_api_key):
    """Test PUT /nodes/update successfully."""
    node_id_to_update = str(uuid.uuid4())
    update_payload = {
        "node_id": node_id_to_update,
        "properties": {
            "party": "Updated Party",
            "district": "Updated District"
        }
    }

    # Configure mock response
    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = [{"node_id": node_id_to_update}]

    headers = {"X-API-KEY": test_api_key}
    response = client.put("/nodes/update", json=update_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    assert response_data["node_id"] == node_id_to_update
    assert response_data["message"] == "Node updated."

    # Verify execute_query
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert f"MATCH (n {{ id: $node_id }})" in call_args[0]
    assert "SET n.party = $props.party" in call_args[0]
    assert "n.district = $props.district" in call_args[0]
    assert "n.updated_at = $props.updated_at" in call_args[0] # Check timestamp update
    assert call_kwargs["parameters"]["node_id"] == node_id_to_update
    assert call_kwargs["parameters"]["props"]["party"] == "Updated Party"
    assert call_kwargs["write"] is True

@pytest.mark.asyncio
async def test_update_node_not_found(client, mock_neo4j_client, test_api_key):
    """Test PUT /nodes/update when the node doesn't exist."""
    node_id_to_update = str(uuid.uuid4())
    update_payload = {
        "node_id": node_id_to_update,
        "properties": {"name": "Does Not Exist"}
    }

    # Configure mock response - query returns empty list
    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = []

    headers = {"X-API-KEY": test_api_key}
    response = client.put("/nodes/update", json=update_payload, headers=headers)

    assert response.status_code == 200 # Endpoint handles not found gracefully
    response_data = response.json()
    assert response_data["success"] is False
    assert response_data["node_id"] == node_id_to_update
    assert "Node not found" in response_data["error"]

@pytest.mark.asyncio
async def test_get_node_success(client, mock_neo4j_client, test_api_key):
    """Test POST /nodes/get successfully."""
    node_id_to_get = str(uuid.uuid4())
    request_payload = {"node_id": node_id_to_get}
    mock_node_data = {
        "id": node_id_to_get,
        "label": "Candidate", # Example property
        "name": "Found Candidate"
    }

    # Configure mock response
    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = [{"n": mock_node_data}]

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/nodes/get", json=request_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    assert response_data["node_data"] == mock_node_data
    assert response_data["error"] is None

    # Verify execute_query
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert "MATCH (n { id: $node_id }) RETURN n" in call_args[0]
    assert call_kwargs["parameters"]["node_id"] == node_id_to_get
    assert call_kwargs["write"] is False

@pytest.mark.asyncio
async def test_get_node_not_found(client, mock_neo4j_client, test_api_key):
    """Test POST /nodes/get when the node doesn't exist."""
    node_id_to_get = str(uuid.uuid4())
    request_payload = {"node_id": node_id_to_get}

    # Configure mock response - empty list
    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = []

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/nodes/get", json=request_payload, headers=headers)

    assert response.status_code == 200 # Endpoint handles not found gracefully
    response_data = response.json()
    assert response_data["success"] is False
    assert response_data["node_data"] is None
    assert response_data["error"] == "Node not found."


@pytest.mark.asyncio
async def test_get_listener_state_found(client, mock_neo4j_client, test_api_key):
    """Test POST /listeners/state/get when state exists."""
    listener_id = "youtube_test_channel"
    request_payload = {"listener_id": listener_id}
    now = datetime.utcnow()
    mock_state_data = {
        "listener_id": listener_id,
        "platform": "YouTube",
        "channel_id": "test_channel",
        "last_checked_timestamp": now.isoformat(), # Neo4j might return string
        "last_processed_item_id": "video123",
        "cursor": None,
        "error_count": 0,
        "last_error_message": None,
        "updated_at": now.isoformat() # Neo4j might return string
    }

    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = [{"ls": mock_state_data}]

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/listeners/state/get", json=request_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    assert response_data["error"] is None
    assert response_data["state"]["listener_id"] == listener_id
    assert response_data["state"]["last_processed_item_id"] == "video123"
    # FastAPI should handle the ISO string conversion back to datetime
    # assert isinstance(response_data["state"]["last_checked_timestamp"], str) # Check pydantic conversion

@pytest.mark.asyncio
async def test_get_listener_state_not_found(client, mock_neo4j_client, test_api_key):
    """Test POST /listeners/state/get when state doesn't exist."""
    listener_id = "youtube_nonexistent_channel"
    request_payload = {"listener_id": listener_id}

    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = [] # No state found

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/listeners/state/get", json=request_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True # Still success, just no data
    assert response_data["state"] is None
    assert response_data["error"] is None


@pytest.mark.asyncio
async def test_set_listener_state(client, mock_neo4j_client, test_api_key):
    """Test POST /listeners/state/set."""
    listener_id = "telegram_test_channel"
    now = datetime.utcnow()
    state_payload = {
        "state": {
            "listener_id": listener_id,
            "platform": "Telegram",
            "channel_id": "tg_test_channel",
            "last_checked_timestamp": now.isoformat(),
            "last_processed_item_id": "message567",
            # updated_at should be handled by the endpoint
        }
    }

    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = [{"id": listener_id}] # Simulate success

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/listeners/state/set", json=state_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    assert "Listener state updated" in response_data["message"]

    # Verify execute_query
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert "MERGE (ls:ListenerState { listener_id: $listener_id })" in call_args[0]
    assert call_kwargs["parameters"]["listener_id"] == listener_id
    assert call_kwargs["parameters"]["props"]["platform"] == "Telegram"
    assert "updated_at" in call_kwargs["parameters"]["props"] # Ensure timestamp was added
    assert call_kwargs["write"] is True

@pytest.mark.asyncio
async def test_get_candidate_context(client, mock_neo4j_client, test_api_key):
    """Test POST /context/candidate."""
    candidate_id = str(uuid.uuid4())
    request_payload = {"candidate_id": candidate_id, "limit": 5}
    now = datetime.utcnow()
    mock_post_data = [
        {"p": {"id": str(uuid.uuid4()), "content": "Post 1", "published_at": now.isoformat(), "platform":"Test", "platform_post_id":"p1", "candidate_id": candidate_id, "channel_id":"c1"}},
        {"p": {"id": str(uuid.uuid4()), "content": "Post 2", "published_at": (now - timedelta(days=1)).isoformat(), "platform":"Test", "platform_post_id":"p2", "candidate_id": candidate_id, "channel_id":"c1"}},
    ]

    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = mock_post_data

    headers = {"X-API-KEY": test_api_key}
    response = client.post("/context/candidate", json=request_payload, headers=headers)

    assert response.status_code == 200
    response_data = response.json()
    assert response_data["success"] is True
    assert len(response_data["posts"]) == 2
    assert response_data["posts"][0]["content"] == "Post 1"
    assert response_data["posts"][1]["content"] == "Post 2"

    # Verify execute_query
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert f"MATCH (c:Candidate {{id: $candidate_id}})<-[:POSTED_BY]-(p:SocialPost)" in call_args[0]
    assert "ORDER BY p.published_at DESC" in call_args[0]
    assert "LIMIT $limit" in call_args[0]
    assert call_kwargs["parameters"]["candidate_id"] == candidate_id
    assert call_kwargs["parameters"]["limit"] == 5
    assert call_kwargs["write"] is False


@pytest.mark.asyncio
async def test_link_post_to_candidate(client, mock_neo4j_client, test_api_key):
    """Test POST /relationships/link-post-to-candidate."""
    post_id = str(uuid.uuid4())
    candidate_id = str(uuid.uuid4())

    mock_neo4j_client.execute_query.reset_mock()
    mock_neo4j_client.execute_query.return_value = [{"relationship_type": "POSTED_BY"}]

    headers = {"X-API-KEY": test_api_key}
    # Use query parameters for this endpoint as defined in MCP
    response = client.post(f"/relationships/link-post-to-candidate?post_id={post_id}&candidate_id={candidate_id}", headers=headers)

    assert response.status_code == 201 # Check for 201 Created
    response_data = response.json()
    assert "Relationship created successfully" in response_data["message"]

    # Verify execute_query
    mock_neo4j_client.execute_query.assert_called_once()
    call_args, call_kwargs = mock_neo4j_client.execute_query.call_args
    assert "MATCH (p:SocialPost {id: $post_id})" in call_args[0]
    assert "MATCH (c:Candidate {id: $candidate_id})" in call_args[0]
    assert "MERGE (p)-[r:POSTED_BY]->(c)" in call_args[0]
    assert call_kwargs["parameters"]["post_id"] == post_id
    assert call_kwargs["parameters"]["candidate_id"] == candidate_id
    assert call_kwargs["write"] is True


@pytest.mark.asyncio
async def test_mcp_unauthorized_access(client):
    """Test accessing a protected MCP endpoint without a valid API key."""
    response = client.post("/nodes/get", json={"node_id": "some-id"}, headers={"X-API-KEY": "invalid-key"})
    assert response.status_code == 403 # Forbidden
    assert "Invalid or missing Internal Service API Key" in response.json()["detail"]

    response_no_key = client.post("/nodes/get", json={"node_id": "some-id"})
    assert response_no_key.status_code == 403 # Forbidden (FastAPI TestClient handles missing header correctly based on auto_error=True)
    assert "Not authenticated" in response_no_key.json()["detail"] # Default message when header is missing

# Add more tests for edge cases, error handling (e.g., Neo4jError),
# different node types, relationship endpoints, etc.