# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Acp2b0nQ6pZxdm1rqNyHrU8HvwxxiegL
"""

# Oppo/database/__init__.py

"""
This file marks the 'database' directory as a Python package.
It can also be used for package-level initialization if needed in the future.
"""

# Currently, no package-level initialization is required.
# Importing key components for easier access (optional)
# from .neo4j_client import Neo4jClient
# from .data_models import SocialPost, Candidate
# from .modern_context_protocol import app as mcp_app

print("Initializing Oppo database package...")