# -*- coding: utf-8 -*-
"""data_models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEorXAjKi8jV_jcAfrM81BMiJeuvSuYG
"""

# Oppo/database/data_models.py

"""
Defines Pydantic models for data structures used throughout the Oppo system,
particularly for interacting with the Neo4j database via the MCP Server.
These models ensure data consistency and provide validation.
"""

from pydantic import BaseModel, Field, HttpUrl
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

# Helper function to generate default UUIDs
def default_uuid():
    return str(uuid.uuid4())

class BaseNode(BaseModel):
    """Base model for all Neo4j nodes, providing a unique ID."""
    node_id: str = Field(default_factory=default_uuid, alias="id") # Use 'id' in Neo4j

    class Config:
        allow_population_by_field_name = True # Allow using 'id' during initialization
        orm_mode = True # Allow compatibility with ORM-like usage if needed


class Candidate(BaseNode):
    """Represents a political candidate."""
    label: str = "Candidate" # Neo4j label
    name: str = Field(..., description="Full name of the candidate")
    party: Optional[str] = Field(None, description="Political party affiliation")
    state: Optional[str] = Field(None, description="State the candidate represents/operates in")
    district: Optional[str] = Field(None, description="Congressional district, if applicable")
    fec_id: Optional[str] = Field(None, description="FEC candidate ID", index=True)
    opensecrets_id: Optional[str] = Field(None, description="OpenSecrets candidate ID")
    ballotpedia_url: Optional[HttpUrl] = Field(None, description="URL to Ballotpedia page")
    campaign_website_url: Optional[HttpUrl] = Field(None, description="URL to official campaign website")
    congress_gov_url: Optional[HttpUrl] = Field(None, description="URL to Congress.gov profile")
    house_press_url: Optional[HttpUrl] = Field(None, description="URL to House press releases page")
    youtube_channel_id: Optional[str] = Field(None, description="YouTube channel ID for monitoring", index=True)
    telegram_channel_id: Optional[str] = Field(None, description="Telegram channel ID/username for monitoring", index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config(BaseNode.Config):
        schema_extra = {
            "example": {
                "id": "uuid-candidate-123",
                "name": "John Doe",
                "party": "Republican",
                "state": "PA",
                "district": "1",
                "fec_id": "H0PA01123",
                "youtube_channel_id": "UCExampleChannelID",
                "telegram_channel_id": "ExampleTelegramChannel"
            }
        }

class SocialPost(BaseNode):
    """Represents a social media post ingested from a monitored source."""
    label: str = "SocialPost" # Neo4j label
    platform: str = Field(..., description="Platform the post originated from (e.g., 'YouTube', 'Telegram')", index=True)
    platform_post_id: str = Field(..., description="Unique identifier for the post on its native platform", index=True)
    candidate_id: str = Field(..., description="Internal node_id of the Candidate who made the post")
    channel_id: str = Field(..., description="Platform-specific channel ID where the post appeared")
    url: Optional[HttpUrl] = Field(None, description="Direct URL to the social media post")
    content: str = Field(..., description="Text content of the post")
    published_at: datetime = Field(..., description="Timestamp when the post was published")
    ingested_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the post was ingested into Oppo")
    raw_data: Optional[Dict[str, Any]] = Field(None, description="Original raw data received from the platform API")

    # --- Analysis Scores ---
    contradiction_score: Optional[float] = Field(None, ge=0, le=1, description="Score indicating likelihood of contradiction (0-1)")
    contradiction_explanation: Optional[str] = Field(None, description="LLM explanation for the contradiction score")
    disinformation_score: Optional[float] = Field(None, ge=0, le=1, description="Score indicating likelihood of disinformation (0-1)")
    disinformation_explanation: Optional[str] = Field(None, description="LLM explanation for the disinformation score")
    fact_check_score: Optional[float] = Field(None, ge=-1, le=1, description="Score indicating factual accuracy (-1: False, 0: Unverifiable, 1: True)")
    fact_check_explanation: Optional[str] = Field(None, description="LLM explanation for the fact-check score, potentially with sources")
    evasion_score: Optional[float] = Field(None, ge=0, le=1, description="Score indicating likelihood of evasive language (0-1)")
    evasion_explanation: Optional[str] = Field(None, description="LLM explanation for the evasion score")
    overall_significance_score: Optional[float] = Field(None, ge=0, le=1, description="Combined score calculated by the Decision Engine")
    analysis_completed_at: Optional[datetime] = Field(None, description="Timestamp when LLM analysis was completed")

    class Config(BaseNode.Config):
        schema_extra = {
            "example": {
                "id": "uuid-post-456",
                "platform": "YouTube",
                "platform_post_id": "dQw4w9WgXcQ",
                "candidate_id": "uuid-candidate-123",
                "channel_id": "UCExampleChannelID",
                "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                "content": "This is the video description or comment text.",
                "published_at": "2024-01-15T10:00:00Z",
                "ingested_at": "2024-01-15T10:05:00Z",
                "contradiction_score": 0.8,
                "contradiction_explanation": "Contradicts statement made on 2023-12-01 regarding policy X.",
                "disinformation_score": 0.2,
                "overall_significance_score": 0.75,
                "analysis_completed_at": "2024-01-15T11:30:00Z"
            }
        }

class ListenerState(BaseModel):
    """Represents the state of a listener for a specific channel."""
    listener_id: str = Field(..., description="Unique ID for the listener instance (e.g., 'youtube_UCExampleChannelID')")
    platform: str = Field(..., description="Platform being listened to (e.g., 'YouTube', 'Telegram')")
    channel_id: str = Field(..., description="Platform-specific channel ID")
    last_checked_timestamp: Optional[datetime] = Field(None, description="Timestamp of the last successful check")
    last_processed_item_id: Optional[str] = Field(None, description="ID of the last item processed (e.g., video ID, message ID)")
    cursor: Optional[str] = Field(None, description="Pagination cursor or token, if applicable")
    error_count: int = Field(default=0, description="Number of consecutive errors encountered")
    last_error_message: Optional[str] = Field(None, description="Details of the last error")
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        orm_mode = True
        schema_extra = {
            "example": {
                "listener_id": "youtube_UCExampleChannelID",
                "platform": "YouTube",
                "channel_id": "UCExampleChannelID",
                "last_checked_timestamp": "2024-01-15T10:00:00Z",
                "last_processed_item_id": "videoId123",
                "updated_at": "2024-01-15T10:05:00Z"
            }
        }

# --- MCP Request/Response Models ---

class MCPQueryRequest(BaseModel):
    """Model for generic Cypher query requests to MCP."""
    cypher: str = Field(..., description="The Cypher query to execute.")
    params: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Parameters for the Cypher query.")

class MCPQueryResponse(BaseModel):
    """Model for generic Cypher query responses from MCP."""
    success: bool
    results: Optional[List[Dict[str, Any]]] = None
    error: Optional[str] = None

class MCPStoreNodeRequest(BaseModel):
    """Model for requesting storage of a single node (Candidate or SocialPost)."""
    node_label: str = Field(..., description="The Neo4j label for the node (e.g., 'Candidate', 'SocialPost')")
    properties: Dict[str, Any] = Field(..., description="Dictionary of node properties.")
    unique_field: Optional[str] = Field(None, description="Optional field name to use for MERGE uniqueness constraint (e.g., 'fec_id', 'platform_post_id').")

class MCPStoreNodeResponse(BaseModel):
    """Model for the response after storing a node."""
    success: bool
    node_id: Optional[str] = None # Return the internal ID of the created/merged node
    message: Optional[str] = None
    error: Optional[str] = None

class MCPUpdateNodeRequest(BaseModel):
    """Model for requesting updates to an existing node."""
    node_id: str = Field(..., description="The internal node_id of the node to update.")
    properties: Dict[str, Any] = Field(..., description="Dictionary of properties to update.")

class MCPUpdateNodeResponse(BaseModel):
    """Model for the response after updating a node."""
    success: bool
    node_id: Optional[str] = None
    message: Optional[str] = None
    error: Optional[str] = None

class MCPGetNodeRequest(BaseModel):
    """Model for requesting retrieval of a node by ID."""
    node_id: str = Field(..., description="The internal node_id of the node to retrieve.")

class MCPGetNodeResponse(BaseModel):
    """Model for the response when retrieving a node."""
    success: bool
    node_data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

class MCPGetListenerStateRequest(BaseModel):
    """Model for requesting listener state."""
    listener_id: str = Field(..., description="Unique ID for the listener instance.")

class MCPGetListenerStateResponse(BaseModel):
    """Model for the response containing listener state."""
    success: bool
    state: Optional[ListenerState] = None
    error: Optional[str] = None

class MCPSetListenerStateRequest(BaseModel):
    """Model for setting/updating listener state."""
    state: ListenerState

class MCPSetListenerStateResponse(BaseModel):
    """Model for the response after setting listener state."""
    success: bool
    message: Optional[str] = None
    error: Optional[str] = None

class MCPGetCandidateContextRequest(BaseModel):
    """Model for requesting historical context for a candidate."""
    candidate_id: str = Field(..., description="Internal node_id of the candidate.")
    limit: int = Field(default=10, description="Maximum number of recent posts to retrieve.")
    before_date: Optional[datetime] = Field(None, description="Retrieve posts published before this date.")

class MCPGetCandidateContextResponse(BaseModel):
    """Model for the response containing candidate context."""
    success: bool
    posts: Optional[List[SocialPost]] = None
    error: Optional[str] = None

# Add more models as needed for relationships, other node types, specific queries, etc.