# -*- coding: utf-8 -*-
"""modern_context_protocol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4PMhGYLpnUn3Trd-p-U-ToRhX_qT7I7
"""

# Oppo/database/modern_context_protocol.py

"""
Modern Context Protocol (MCP) Server.

A FastAPI application acting as a secure gateway to the Neo4j database.
It exposes endpoints for other internal Oppo services (Listeners, Analysis Engine,
Data Collection Scripts) to interact with the database without requiring direct
database credentials or access.

Handles data validation using Pydantic models from data_models.py and uses
the Neo4jClient for database operations. Implements basic API key security.
"""

import os
import logging
from fastapi import FastAPI, Depends, HTTPException, Security, status
from fastapi.security import APIKeyHeader
from typing import List, Dict, Any, Optional
from datetime import datetime

# Import local modules
from .neo4j_client import Neo4jClient
from .data_models import (
    Candidate, SocialPost, ListenerState,
    MCPQueryRequest, MCPQueryResponse,
    MCPStoreNodeRequest, MCPStoreNodeResponse,
    MCPUpdateNodeRequest, MCPUpdateNodeResponse,
    MCPGetNodeRequest, MCPGetNodeResponse,
    MCPGetListenerStateRequest, MCPGetListenerStateResponse,
    MCPSetListenerStateRequest, MCPSetListenerStateResponse,
    MCPGetCandidateContextRequest, MCPGetCandidateContextResponse
)
from neo4j.exceptions import Neo4jError

# Configure logging
logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO").upper())
logger = logging.getLogger(__name__)

# --- Configuration & Initialization ---

# API Key Security
API_KEY_NAME = "X-API-KEY" # Standard header name for API keys
api_key_header = APIKeyHeader(name=API_KEY_NAME, auto_error=True)
INTERNAL_SERVICE_API_KEY = os.environ.get("INTERNAL_SERVICE_API_KEY")

if not INTERNAL_SERVICE_API_KEY:
    logger.warning("INTERNAL_SERVICE_API_KEY environment variable not set. MCP security is disabled.")
    # In a real deployment, you might want to raise an error or exit if the key is missing.
    # raise ValueError("INTERNAL_SERVICE_API_KEY must be set for MCP server.")

async def verify_api_key(key: str = Security(api_key_header)):
    """Dependency to verify the provided API key."""
    if not INTERNAL_SERVICE_API_KEY:
         logger.warning("Skipping API key verification as INTERNAL_SERVICE_API_KEY is not set.")
         return # Allow access if key is not configured (for local dev maybe)

    if key == INTERNAL_SERVICE_API_KEY:
        return key
    else:
        logger.warning(f"Invalid API Key received: {key}")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid or missing Internal Service API Key"
        )

# FastAPI App Initialization
app = FastAPI(
    title="Oppo Modern Context Protocol (MCP) Server",
    description="Secure gateway for Neo4j database interactions within the Oppo system.",
    version="0.1.0",
    dependencies=[Depends(verify_api_key)] # Apply API key security to all routes
)

# Neo4j Client Instance (managed lifespan)
neo4j_client: Optional[Neo4jClient] = None

@app.on_event("startup")
async def startup_event():
    """Initialize Neo4j client on application startup."""
    global neo4j_client
    logger.info("MCP Server starting up...")
    try:
        neo4j_client = Neo4jClient()
        logger.info("Neo4j client initialized successfully for MCP.")
    except Exception as e:
        logger.critical(f"Failed to initialize Neo4j client during MCP startup: {e}")
        # Depending on policy, you might want to prevent startup
        neo4j_client = None # Ensure it's None if initialization failed

@app.on_event("shutdown")
async def shutdown_event():
    """Close Neo4j client on application shutdown."""
    logger.info("MCP Server shutting down...")
    if neo4j_client:
        neo4j_client.close()
        logger.info("Neo4j client closed by MCP.")

def get_db() -> Neo4jClient:
    """Dependency to get the initialized Neo4j client."""
    if neo4j_client is None:
         logger.error("Neo4j client is not available.")
         raise HTTPException(
             status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
             detail="Database connection not available."
         )
    return neo4j_client

# --- API Endpoints ---

@app.get("/health", status_code=status.HTTP_200_OK, dependencies=[]) # No auth for health check
async def health_check():
    """Basic health check endpoint."""
    logger.debug("Health check endpoint called.")
    # More advanced check: try a simple read query?
    # try:
    #     if neo4j_client:
    #         neo4j_client.execute_query("RETURN 1", write=False)
    #     else:
    #         raise ServiceUnavailable("Client not initialized")
    #     return {"status": "ok", "database_connection": "ok"}
    # except Exception as e:
    #     logger.error(f"Health check failed database check: {e}")
    #     raise HTTPException(status_code=503, detail=f"Database connection error: {e}")
    return {"status": "ok"}

# --- Generic Query Endpoint (Use with caution) ---

@app.post("/query", response_model=MCPQueryResponse)
async def execute_cypher_query(
    request: MCPQueryRequest,
    db: Neo4jClient = Depends(get_db)
):
    """
    Executes an arbitrary Cypher query.
    **Warning:** Exposing raw Cypher execution can be a security risk.
    Use specific endpoints for common operations where possible.
    """
    logger.info(f"Executing generic Cypher query via MCP: {request.cypher[:100]}...")
    try:
        # Determine if it's a write query based on keywords (basic check)
        is_write = any(keyword in request.cypher.upper() for keyword in ["CREATE", "MERGE", "SET", "DELETE", "REMOVE"])
        results = db.execute_query(request.cypher, request.params, write=is_write)
        return MCPQueryResponse(success=True, results=results)
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError during generic query execution: {e}")
        return MCPQueryResponse(success=False, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error during generic query execution: {e}")
        return MCPQueryResponse(success=False, error=f"Unexpected error: {e}")

# --- Node Management Endpoints ---

@app.post("/nodes/store", response_model=MCPStoreNodeResponse)
async def store_node(
    request: MCPStoreNodeRequest,
    db: Neo4jClient = Depends(get_db)
):
    """
    Stores (Creates or Merges) a single node (e.g., Candidate, SocialPost) in Neo4j.
    Uses MERGE if unique_field is provided, otherwise CREATE.
    """
    logger.info(f"MCP: Storing node with label '{request.node_label}'")
    properties = request.properties.copy() # Avoid modifying the original request

    # Ensure standard fields are present and correctly typed
    properties['updated_at'] = datetime.utcnow()
    if 'created_at' not in properties:
        properties['created_at'] = datetime.utcnow()
    if 'id' not in properties:
         # If using UUIDs generated by the model, they should be in properties already.
         # If generating here, ensure it's consistent.
         # properties['id'] = str(uuid.uuid4()) # Or retrieve from model default
         pass # Assume ID is handled by the pydantic model or passed in properties


    # Prepare parameters for Cypher, ensuring nested dicts/lists are handled if necessary
    # The Neo4jClient's _serialize_value handles datetime etc.
    params = {'props': properties}

    cypher = ""
    node_var = "n" # Variable name in Cypher

    if request.unique_field and request.unique_field in properties:
        # Use MERGE based on the unique field
        unique_value = properties[request.unique_field]
        params['unique_value'] = unique_value
        cypher = f"""
        MERGE ({node_var}:{request.node_label} {{ {request.unique_field}: $unique_value }})
        ON CREATE SET {node_var} = $props
        ON MATCH SET {node_var} += $props, {node_var}.updated_at = datetime()
        RETURN {node_var}.id as node_id
        """
        logger.debug(f"MCP Store: Using MERGE on {request.node_label}.{request.unique_field}")
    elif 'id' in properties:
         # Use MERGE based on the internal ID (preferred way to update/create)
        params['node_id'] = properties['id']
        cypher = f"""
        MERGE ({node_var}:{request.node_label} {{ id: $node_id }})
        ON CREATE SET {node_var} = $props
        ON MATCH SET {node_var} += $props, {node_var}.updated_at = datetime()
        RETURN {node_var}.id as node_id
        """
        logger.debug(f"MCP Store: Using MERGE on {request.node_label}.id")
    else:
        # Use CREATE if no unique field or ID is specified (less common for updates)
        cypher = f"""
        CREATE ({node_var}:{request.node_label})
        SET {node_var} = $props
        RETURN {node_var}.id as node_id
        """
        logger.debug(f"MCP Store: Using CREATE for {request.node_label}")


    try:
        result = db.execute_query(cypher, parameters=params, write=True)
        if result and 'node_id' in result[0]:
            node_id = result[0]['node_id']
            logger.info(f"MCP: Node '{node_id}' stored successfully.")
            return MCPStoreNodeResponse(success=True, node_id=node_id, message="Node stored successfully.")
        else:
             logger.error(f"MCP: Node storage query did not return node_id. Cypher: {cypher}")
             return MCPStoreNodeResponse(success=False, error="Node stored, but failed to retrieve ID.")
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError storing node: {e}")
        return MCPStoreNodeResponse(success=False, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error storing node: {e}")
        return MCPStoreNodeResponse(success=False, error=f"Unexpected error: {e}")


@app.put("/nodes/update", response_model=MCPUpdateNodeResponse)
async def update_node(
    request: MCPUpdateNodeRequest,
    db: Neo4jClient = Depends(get_db)
):
    """Updates properties of an existing node identified by its internal ID."""
    logger.info(f"MCP: Updating node '{request.node_id}'")
    properties_to_update = request.properties.copy()
    properties_to_update['updated_at'] = datetime.utcnow() # Always update timestamp

    # Prepare parameters
    params = {'node_id': request.node_id, 'props': properties_to_update}

    # Build SET clauses dynamically to avoid overwriting the entire node
    set_clauses = [f"n.{key} = $props.{key}" for key in properties_to_update]
    if not set_clauses:
        return MCPUpdateNodeResponse(success=False, node_id=request.node_id, error="No properties provided for update.")

    cypher = f"""
    MATCH (n {{ id: $node_id }})
    SET {', '.join(set_clauses)}
    RETURN n.id as node_id
    """

    try:
        result = db.execute_query(cypher, parameters=params, write=True)
        if result and 'node_id' in result[0]:
            node_id = result[0]['node_id']
            logger.info(f"MCP: Node '{node_id}' updated successfully.")
            return MCPUpdateNodeResponse(success=True, node_id=node_id, message="Node updated.")
        else:
            # This could mean the node with the given ID wasn't found
            logger.warning(f"MCP: Node update query did not return ID or node '{request.node_id}' not found.")
            return MCPUpdateNodeResponse(success=False, node_id=request.node_id, error="Node not found or update failed.")
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError updating node: {e}")
        return MCPUpdateNodeResponse(success=False, node_id=request.node_id, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error updating node: {e}")
        return MCPUpdateNodeResponse(success=False, node_id=request.node_id, error=f"Unexpected error: {e}")


@app.post("/nodes/get", response_model=MCPGetNodeResponse)
async def get_node(
    request: MCPGetNodeRequest,
    db: Neo4jClient = Depends(get_db)
):
    """Retrieves a single node by its internal ID."""
    logger.info(f"MCP: Getting node '{request.node_id}'")
    cypher = "MATCH (n { id: $node_id }) RETURN n"
    params = {'node_id': request.node_id}

    try:
        result = db.execute_query(cypher, parameters=params, write=False)
        if result and 'n' in result[0]:
            node_data = result[0]['n'] # Neo4j driver returns node properties as a dict
            logger.info(f"MCP: Node '{request.node_id}' retrieved successfully.")
            return MCPGetNodeResponse(success=True, node_data=node_data)
        else:
            logger.warning(f"MCP: Node '{request.node_id}' not found.")
            return MCPGetNodeResponse(success=False, error="Node not found.")
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError getting node: {e}")
        return MCPGetNodeResponse(success=False, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error getting node: {e}")
        return MCPGetNodeResponse(success=False, error=f"Unexpected error: {e}")

# --- Listener State Endpoints ---

@app.post("/listeners/state/get", response_model=MCPGetListenerStateResponse)
async def get_listener_state(
    request: MCPGetListenerStateRequest,
    db: Neo4jClient = Depends(get_db)
):
    """Retrieves the last known state for a specific listener."""
    logger.info(f"MCP: Getting state for listener '{request.listener_id}'")
    cypher = "MATCH (ls:ListenerState { listener_id: $listener_id }) RETURN ls"
    params = {'listener_id': request.listener_id}
    try:
        result = db.execute_query(cypher, params, write=False)
        if result and 'ls' in result[0]:
             # Neo4j driver returns properties; convert to Pydantic model
            state_data = result[0]['ls']
            # Handle potential datetime string conversion if needed (driver usually handles it)
            if isinstance(state_data.get('last_checked_timestamp'), str):
                 state_data['last_checked_timestamp'] = datetime.fromisoformat(state_data['last_checked_timestamp'].replace('Z', '+00:00'))
            if isinstance(state_data.get('updated_at'), str):
                 state_data['updated_at'] = datetime.fromisoformat(state_data['updated_at'].replace('Z', '+00:00'))

            listener_state = ListenerState(**state_data)
            logger.info(f"MCP: State retrieved for listener '{request.listener_id}'.")
            return MCPGetListenerStateResponse(success=True, state=listener_state)
        else:
            logger.info(f"MCP: No state found for listener '{request.listener_id}'.")
            # Return success=True but state=None to indicate not found, not an error
            return MCPGetListenerStateResponse(success=True, state=None)
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError getting listener state: {e}")
        return MCPGetListenerStateResponse(success=False, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error getting listener state: {e}")
        return MCPGetListenerStateResponse(success=False, error=f"Unexpected error: {e}")


@app.post("/listeners/state/set", response_model=MCPSetListenerStateResponse)
async def set_listener_state(
    request: MCPSetListenerStateRequest,
    db: Neo4jClient = Depends(get_db)
):
    """Sets (Creates or Updates) the state for a specific listener."""
    listener_id = request.state.listener_id
    logger.info(f"MCP: Setting state for listener '{listener_id}'")

    # Use Pydantic model's dict() method for serialization, handling defaults
    # Exclude unset fields to avoid overwriting with None if not provided
    state_properties = request.state.dict(exclude_unset=True)
    state_properties['updated_at'] = datetime.utcnow() # Always set update time

    params = {'listener_id': listener_id, 'props': state_properties}

    # MERGE based on listener_id to handle both creation and update
    cypher = """
    MERGE (ls:ListenerState { listener_id: $listener_id })
    ON CREATE SET ls = $props
    ON MATCH SET ls += $props
    RETURN ls.listener_id as id
    """
    try:
        result = db.execute_query(cypher, params, write=True)
        if result and 'id' in result[0]:
            logger.info(f"MCP: State set successfully for listener '{listener_id}'.")
            return MCPSetListenerStateResponse(success=True, message="Listener state updated.")
        else:
             logger.error(f"MCP: Failed to set listener state for '{listener_id}'. Query returned no ID.")
             return MCPSetListenerStateResponse(success=False, error="Failed to set state in database.")
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError setting listener state: {e}")
        return MCPSetListenerStateResponse(success=False, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error setting listener state: {e}")
        return MCPSetListenerStateResponse(success=False, error=f"Unexpected error: {e}")


# --- Context Retrieval Endpoints ---

@app.post("/context/candidate", response_model=MCPGetCandidateContextResponse)
async def get_candidate_context(
    request: MCPGetCandidateContextRequest,
    db: Neo4jClient = Depends(get_db)
):
    """Retrieves recent SocialPost context for a given candidate."""
    logger.info(f"MCP: Getting context for candidate '{request.candidate_id}', limit={request.limit}")

    params = {
        'candidate_id': request.candidate_id,
        'limit': request.limit
    }
    # Base query to match candidate and related posts
    cypher = """
    MATCH (c:Candidate {id: $candidate_id})<-[:POSTED_BY]-(p:SocialPost)
    """
    # Optional filtering by date
    if request.before_date:
        params['before_date'] = request.before_date
        cypher += "WHERE p.published_at < $before_date "

    # Ordering and limiting
    cypher += """
    RETURN p
    ORDER BY p.published_at DESC
    LIMIT $limit
    """

    try:
        results = db.execute_query(cypher, params, write=False)
        posts = []
        if results:
            for record in results:
                post_data = record['p']
                 # Convert to Pydantic model, handling potential datetime strings
                if isinstance(post_data.get('published_at'), str):
                    post_data['published_at'] = datetime.fromisoformat(post_data['published_at'].replace('Z', '+00:00'))
                if isinstance(post_data.get('ingested_at'), str):
                    post_data['ingested_at'] = datetime.fromisoformat(post_data['ingested_at'].replace('Z', '+00:00'))
                if isinstance(post_data.get('analysis_completed_at'), str):
                    post_data['analysis_completed_at'] = datetime.fromisoformat(post_data['analysis_completed_at'].replace('Z', '+00:00'))

                posts.append(SocialPost(**post_data))
        logger.info(f"MCP: Retrieved {len(posts)} context posts for candidate '{request.candidate_id}'.")
        return MCPGetCandidateContextResponse(success=True, posts=posts)
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError getting candidate context: {e}")
        return MCPGetCandidateContextResponse(success=False, error=f"Neo4jError: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error getting candidate context: {e}")
        return MCPGetCandidateContextResponse(success=False, error=f"Unexpected error: {e}")


# --- Relationship Management (Example: Linking Post to Candidate) ---

@app.post("/relationships/link-post-to-candidate", status_code=status.HTTP_201_CREATED)
async def link_post_to_candidate(
    post_id: str,
    candidate_id: str,
    db: Neo4jClient = Depends(get_db)
):
    """Creates a POSTED_BY relationship between a SocialPost and a Candidate."""
    logger.info(f"MCP: Linking post '{post_id}' to candidate '{candidate_id}'")
    cypher = """
    MATCH (p:SocialPost {id: $post_id})
    MATCH (c:Candidate {id: $candidate_id})
    MERGE (p)-[r:POSTED_BY]->(c)
    RETURN type(r) as relationship_type
    """
    params = {'post_id': post_id, 'candidate_id': candidate_id}
    try:
        result = db.execute_query(cypher, params, write=True)
        if result and result[0].get('relationship_type') == 'POSTED_BY':
            logger.info(f"MCP: Successfully linked post '{post_id}' to candidate '{candidate_id}'.")
            return {"message": "Relationship created successfully."}
        else:
            logger.warning(f"MCP: Failed to verify relationship creation between post '{post_id}' and candidate '{candidate_id}'. Nodes might be missing.")
            # Check if nodes exist before attempting merge?
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Post or Candidate node not found, or relationship merge failed.")
    except Neo4jError as e:
        logger.error(f"MCP: Neo4jError linking post to candidate: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Database error: {e}")
    except Exception as e:
        logger.error(f"MCP: Unexpected error linking post to candidate: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Unexpected server error: {e}")


# Add more specific endpoints as needed for:
# - Finding candidates by criteria (FEC ID, name, etc.)
# - Finding posts by platform ID
# - Complex graph traversals for reporting
# - Deleting nodes/relationships (with caution)

# --- Main block for running directly (for development/testing) ---
if __name__ == "__main__":
    import uvicorn
    logger.info("Starting MCP Server directly using Uvicorn...")
    # Ensure API key is set for local testing if required
    if not INTERNAL_SERVICE_API_KEY:
        logger.warning("Running MCP locally without INTERNAL_SERVICE_API_KEY set.")
    # Use port 8001 as suggested in README/docker-compose
    uvicorn.run(app, host="0.0.0.0", port=8001, log_level=os.environ.get("LOG_LEVEL", "info").lower())