# -*- coding: utf-8 -*-
"""neo4j_client

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G35UljwmFz4UpAuo79-ycqTIIUCPpvD7
"""

# Oppo/database/neo4j_client.py

"""
Provides a client class for interacting with the Neo4j graph database.
Handles connection management and execution of Cypher queries.
Reads configuration from environment variables.
"""

import os
import logging
from neo4j import GraphDatabase, Driver, Session, Transaction, Result
from neo4j.exceptions import ServiceUnavailable, AuthError, Neo4jError
from tenacity import retry, stop_after_attempt, wait_fixed, retry_if_exception_type
from typing import Optional, Dict, Any, List, Callable
from datetime import datetime, date, time, timedelta
from .data_models import BaseNode # Import base model for type hinting if needed

# Configure logging
logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO").upper())
logger = logging.getLogger(__name__)

# Environment variables for connection
NEO4J_URI = os.environ.get("NEO4J_URI", "neo4j://localhost:7687")
NEO4J_USERNAME = os.environ.get("NEO4J_USERNAME", "neo4j")
NEO4J_PASSWORD = os.environ.get("NEO4J_PASSWORD", "password") # Use a secure default or raise error if not set

# Retry configuration for database operations
RETRY_ATTEMPTS = 3
RETRY_WAIT_SECONDS = 2

class Neo4jClient:
    """
    A client for connecting to and interacting with a Neo4j database instance.
    Manages the driver and sessions, providing methods for executing queries.
    """

    _driver: Optional[Driver] = None

    def __init__(self, uri: str = NEO4J_URI, user: str = NEO4J_USERNAME, password: str = NEO4J_PASSWORD):
        """
        Initializes the Neo4jClient.

        Args:
            uri (str): The connection URI for the Neo4j database.
            user (str): The username for database authentication.
            password (str): The password for database authentication.
        """
        self.uri = uri
        self.user = user
        self.password = password
        self._connect()

    @retry(
        stop=stop_after_attempt(RETRY_ATTEMPTS),
        wait=wait_fixed(RETRY_WAIT_SECONDS),
        retry=retry_if_exception_type((ServiceUnavailable, AuthError, OSError)),
        reraise=True # Reraise the exception if all retries fail
    )
    def _connect(self):
        """Establishes the connection to the Neo4j database using the driver."""
        logger.info(f"Attempting to connect to Neo4j at {self.uri}...")
        try:
            self._driver = GraphDatabase.driver(self.uri, auth=(self.user, self.password))
            self._driver.verify_connectivity()
            logger.info("Neo4j connection successful.")
            self._ensure_constraints_indexes()
        except AuthError:
            logger.error(f"Neo4j authentication failed for user '{self.user}'. Check credentials.")
            raise
        except ServiceUnavailable as e:
            logger.error(f"Neo4j service unavailable at {self.uri}. Retrying... Error: {e}")
            raise
        except Exception as e:
            logger.error(f"Failed to connect to Neo4j or verify connectivity: {e}")
            raise # Reraise other unexpected exceptions

    def _ensure_constraints_indexes(self):
        """
        Ensures necessary constraints and indexes exist in the database.
        This should be run once on initialization.
        """
        logger.info("Ensuring database constraints and indexes...")
        # Use try-except as attempting to create existing constraints/indexes raises errors
        constraints_indexes = [
            # Unique node IDs (using 'id' property)
            "CREATE CONSTRAINT unique_node_id IF NOT EXISTS FOR (n:BaseNode) REQUIRE n.id IS UNIQUE",
            # Candidate constraints/indexes
            "CREATE CONSTRAINT unique_candidate_id IF NOT EXISTS FOR (c:Candidate) REQUIRE c.id IS UNIQUE",
            "CREATE INDEX candidate_fec_id IF NOT EXISTS FOR (c:Candidate) ON (c.fec_id)",
            "CREATE INDEX candidate_yt_channel_id IF NOT EXISTS FOR (c:Candidate) ON (c.youtube_channel_id)",
            "CREATE INDEX candidate_tg_channel_id IF NOT EXISTS FOR (c:Candidate) ON (c.telegram_channel_id)",
            # SocialPost constraints/indexes
            "CREATE CONSTRAINT unique_socialpost_id IF NOT EXISTS FOR (p:SocialPost) REQUIRE p.id IS UNIQUE",
            "CREATE INDEX socialpost_platform_post_id IF NOT EXISTS FOR (p:SocialPost) ON (p.platform_post_id)",
            "CREATE INDEX socialpost_platform IF NOT EXISTS FOR (p:SocialPost) ON (p.platform)",
            "CREATE INDEX socialpost_published_at IF NOT EXISTS FOR (p:SocialPost) ON (p.published_at)",
            # ListenerState constraints/indexes
            "CREATE CONSTRAINT unique_listener_id IF NOT EXISTS FOR (ls:ListenerState) REQUIRE ls.listener_id IS UNIQUE",
            "CREATE INDEX listener_platform IF NOT EXISTS FOR (ls:ListenerState) ON (ls.platform)",
            "CREATE INDEX listener_channel_id IF NOT EXISTS FOR (ls:ListenerState) ON (ls.channel_id)",
        ]
        try:
            with self.get_session(write=True) as session:
                for statement in constraints_indexes:
                    try:
                        logger.debug(f"Executing schema statement: {statement}")
                        session.run(statement)
                    except Neo4jError as e:
                        # Ignore errors indicating the constraint/index already exists
                        if "already exists" in str(e).lower():
                            logger.debug(f"Schema item already exists: {statement}")
                        else:
                            logger.warning(f"Could not apply schema statement '{statement}': {e}")
                            # Depending on policy, you might want to raise here for critical constraints
            logger.info("Database constraints and indexes ensured.")
        except Exception as e:
            logger.error(f"Failed during constraint/index creation: {e}")
            # Decide if this is a fatal error

    def close(self):
        """Closes the Neo4j driver connection."""
        if self._driver:
            logger.info("Closing Neo4j connection.")
            self._driver.close()
            self._driver = None

    def get_session(self, write: bool = False) -> Session:
        """
        Gets a Neo4j session from the driver.

        Args:
            write (bool): If True, returns a session suitable for write operations.
                          Otherwise, returns a session for read operations.

        Returns:
            Session: A Neo4j session object.

        Raises:
            ConnectionError: If the driver is not initialized.
        """
        if not self._driver:
            logger.error("Neo4j driver not initialized. Cannot get session.")
            raise ConnectionError("Neo4j driver not initialized.")
        if write:
            return self._driver.session(database=self._driver.database) # Default database for writes
        else:
            # Consider using specific database if replicas are configured
            return self._driver.session(database=self._driver.database) # Default database for reads

    @staticmethod
    def _serialize_value(value: Any) -> Any:
        """Recursively converts datetime objects to ISO format strings for Neo4j compatibility."""
        if isinstance(value, (datetime, date, time)):
            return value.isoformat()
        elif isinstance(value, timedelta):
            return value.total_seconds() # Represent timedelta as seconds
        elif isinstance(value, dict):
            return {k: Neo4jClient._serialize_value(v) for k, v in value.items()}
        elif isinstance(value, list):
            return [Neo4jClient._serialize_value(item) for item in value]
        elif isinstance(value, BaseNode): # Handle Pydantic models if passed directly
             # Use .dict(by_alias=True) if you use aliases like 'id' for 'node_id'
            return Neo4jClient._serialize_value(value.dict(by_alias=True, exclude_unset=True))
        return value

    @retry(
        stop=stop_after_attempt(RETRY_ATTEMPTS),
        wait=wait_fixed(RETRY_WAIT_SECONDS),
        retry=retry_if_exception_type(ServiceUnavailable), # Retry on connection issues
        reraise=True
    )
    def execute_query(
        self,
        query: str,
        parameters: Optional[Dict[str, Any]] = None,
        write: bool = False
    ) -> List[Dict[str, Any]]:
        """
        Executes a Cypher query against the database.

        Args:
            query (str): The Cypher query string.
            parameters (Optional[Dict[str, Any]]): Dictionary of parameters for the query.
                                                 Datetime objects will be serialized.
            write (bool): Indicates if the query performs write operations.

        Returns:
            List[Dict[str, Any]]: A list of records, where each record is a dictionary.

        Raises:
            Neo4jError: If the query execution fails.
            ConnectionError: If the client is not connected.
            Exception: For other unexpected errors.
        """
        if not self._driver:
            logger.error("Neo4j driver not initialized. Cannot execute query.")
            raise ConnectionError("Neo4j driver not initialized.")

        # Serialize parameters, especially datetime objects
        serialized_params = self._serialize_value(parameters) if parameters else {}

        logger.debug(f"Executing Cypher (write={write}): {query} with params: {serialized_params}")

        results = []
        try:
            with self.get_session(write=write) as session:
                # Choose the appropriate transaction function based on write flag
                tx_func: Callable[[Transaction, str, Dict], Result]
                if write:
                    tx_func = lambda tx, q, p: tx.run(q, p)
                    result = session.execute_write(tx_func, query, serialized_params)
                else:
                    tx_func = lambda tx, q, p: tx.run(q, p)
                    result = session.execute_read(tx_func, query, serialized_params)

                # Process results into a list of dictionaries
                results = [record.data() for record in result]
                logger.debug(f"Query executed successfully. Rows returned: {len(results)}")
                return results
        except ServiceUnavailable as e:
            logger.warning(f"Neo4j service unavailable during query execution. Retrying... Error: {e}")
            self._connect() # Attempt to reconnect before retrying
            raise # Reraise to trigger tenacity retry
        except Neo4jError as e:
            logger.error(f"Neo4j query failed: {e}\nQuery: {query}\nParams: {serialized_params}")
            raise # Reraise Neo4j specific errors
        except Exception as e:
            logger.error(f"An unexpected error occurred during query execution: {e}")
            raise # Reraise other exceptions

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.close()

# Example usage (optional, for testing)
if __name__ == "__main__":
    try:
        client = Neo4jClient()
        logger.info("Neo4jClient instantiated successfully.")

        # Example: Create a dummy node (write operation)
        # try:
        #     client.execute_query(
        #         "MERGE (t:TestNode {name: $name}) SET t.timestamp = $ts RETURN t",
        #         parameters={"name": "Neo4jClientTest", "ts": datetime.utcnow()},
        #         write=True
        #     )
        #     logger.info("Test node created or merged.")
        # except Exception as e:
        #      logger.error(f"Failed to create test node: {e}")

        # Example: Read the node (read operation)
        # try:
        #     nodes = client.execute_query(
        #         "MATCH (t:TestNode {name: $name}) RETURN t.name as name, t.timestamp as timestamp",
        #         parameters={"name": "Neo4jClientTest"},
        #         write=False
        #     )
        #     if nodes:
        #         logger.info(f"Test node found: {nodes[0]}")
        #     else:
        #         logger.warning("Test node not found.")
        # except Exception as e:
        #      logger.error(f"Failed to read test node: {e}")

        client.close()
        logger.info("Neo4jClient closed.")

    except Exception as e:
        logger.critical(f"Failed to initialize or use Neo4jClient: {e}")