# -*- coding: utf-8 -*-
"""server.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPsOFlUl9ThGLWyp5taVARLpqG8dTlR_
"""

# File: Oppo/a2a_host/server.py
# Purpose: Main FastAPI application setup, lifespan manager, ingestion endpoint, analysis orchestration.

import logging
import os
from contextlib import asynccontextmanager
from typing import Optional, Dict, Any, List
import asyncio # For triggering async tasks
import requests # For MCP session

from fastapi import FastAPI, Depends, HTTPException, Request, status, Body, BackgroundTasks
from fastapi.security import OAuth2PasswordRequestForm
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, ValidationError

# --- Project Imports ---
# Configuration
from .config import (
    MCP_SERVER_URL, INTERNAL_SERVICE_API_KEY, LOG_LEVEL, # URLs and Keys
    # LLM provider/model selections are used by analysis modules via llm_interface
)
# Authentication
from .auth import (
    authenticate_user, create_access_token, get_current_active_user, verify_internal_api_key,
    Token, User
)
# API Routers
from .routers import api_router as main_api_router # Main router for external A2A agents
# Database Models (used for request body validation)
try:
    from database.data_models import SocialPost
    MODELS_LOADED = True
except ImportError:
     # Ensure logger is available if config import failed
     log_level_env = os.getenv("LOG_LEVEL", "INFO").upper()
     logging.basicConfig(level=getattr(logging, log_level_env, logging.INFO), format='%(asctime)s:%(levelname)s:%(name)s:%(lineno)d:%(message)s')
     logger = logging.getLogger(__name__)
     logger.error("Could not import data models for a2a_host server. Payload validation might fail.")
     MODELS_LOADED = False
     class SocialPost(BaseModel): pass # Dummy model
# Analysis Components (instantiated during lifespan)
try:
    from analysis import (
        FactChecker, ContradictionDetector, EvasionDetector,
        DisinformationAnalyzer, DecisionEngine, ReportGenerator,
        LLMInterface # The core LLM interaction layer
    )
    ANALYSIS_LOADED = True
except ImportError as e:
     logging.error(f"Could not import all analysis modules: {e}. Analysis features disabled.")
     ANALYSIS_LOADED = False
     # Define dummy classes if needed for lifespan setup
     class LLMInterface: pass
     class ReportGenerator: pass
     class FactChecker: pass
     class ContradictionDetector: pass
     class EvasionDetector: pass
     class DisinformationAnalyzer: pass
     class DecisionEngine: pass

# A2A Protocol for triggering distribution
try:
    from .a2a_protocol import trigger_distribution
    DISTRIBUTION_LOADED = True
except ImportError as e:
     logging.error(f"Could not import trigger_distribution from a2a_protocol: {e}. A2A distribution disabled.")
     DISTRIBUTION_LOADED = False
     def trigger_distribution(*args, **kwargs): # Dummy function
          logging.warning("A2A distribution trigger called but is not available.")
          pass

# --- Logging Setup ---
# Ensure logging is configured using the level from config
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format='%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - %(message)s',
    force=True # Ensure logger is configured
)
logger = logging.getLogger(__name__)


# --- Global State (Managed by Lifespan) ---
# These are initialized at startup
mcp_session: Optional[requests.Session] = None # Session for calling MCP
llm_interface: Optional[LLMInterface] = None
report_generator: Optional[ReportGenerator] = None
fact_checker: Optional[FactChecker] = None
contradiction_detector: Optional[ContradictionDetector] = None
evasion_detector: Optional[EvasionDetector] = None
disinformation_analyzer: Optional[DisinformationAnalyzer] = None
decision_engine: Optional[DecisionEngine] = None

# --- Helper Function for MCP Calls (used by analysis orchestration & report gen) ---
async def call_mcp_api(
    method: str,
    endpoint: str,
    json_payload: Optional[Dict] = None,
    params: Optional[Dict] = None
) -> Dict[str, Any]:
    """
    Async helper to call the MCP Server API using the global session.
    Returns a dict, including an 'error' key on failure.
    """
    global mcp_session
    if not MCP_SERVER_URL or mcp_session is None:
        logger.error("MCP_SERVER_URL or MCP session not configured/initialized.")
        return {"status": "error", "error": "MCP connection not available"}

    url = f"{MCP_SERVER_URL.rstrip('/')}/{endpoint.lstrip('/')}"
    log_payload_str = f"{str(json_payload)[:200]}..." if json_payload else "None"
    logger.debug(f"MCP Call (from A2A Host): {method.upper()} {url} Params: {params} Payload: {log_payload_str}")
    loop = asyncio.get_running_loop()
    try:
        # Run synchronous requests call in a threadpool to avoid blocking asyncio event loop
        response = await loop.run_in_executor(
            None, # Use default executor
            lambda: mcp_session.request(
                method,
                url,
                json=json_payload,
                params=params,
                timeout=45 # Longer timeout for potentially complex MCP queries/updates
            )
        )
        response.raise_for_status() # Check for 4xx/5xx errors first
        data = response.json()
        # Assume MCP returns {'status': 'success', ...} on success
        if isinstance(data, dict) and data.get("status") == "success":
            return data # Return the full success response
        else:
            error_msg = data.get('message', data.get('detail', 'Unknown MCP error structure')) if isinstance(data, dict) else f"Non-dict response: {str(data)[:200]}"
            logger.error(f"MCP API returned non-success status for {method} {endpoint}: {error_msg}")
            return {"status": "error", "error": error_msg}
    except requests.exceptions.HTTPError as e:
        error_detail = f"HTTP Error {e.response.status_code}"
        try: error_detail = e.response.json().get('detail', error_detail)
        except: pass
        logger.error(f"HTTP Error calling MCP {method} {endpoint}: {error_detail}", exc_info=False)
        return {"status": "error", "error": error_detail}
    except requests.exceptions.RequestException as e:
        logger.error(f"Network Error calling MCP {method} {endpoint}: {e}", exc_info=False)
        return {"status": "error", "error": "Network Error"}
    except Exception as e:
        logger.error(f"Unexpected error calling MCP {method} {endpoint}: {e}", exc_info=True)
        return {"status": "error", "error": "Unexpected Processing Error"}


# --- Analysis Orchestration Task ---
async def trigger_analysis_task(post_node_id: str, post_payload: Dict):
    """
    Wrapper to run the analysis pipeline in the background.
    Handles potential errors during the pipeline execution.
    """
    try:
        await run_analysis_pipeline(post_node_id, post_payload)
    except Exception as e:
        logger.error(f"Unhandled exception in background analysis task for post node {post_node_id}: {e}", exc_info=True)
        # Optionally: Update post status in DB to 'ANALYSIS_FAILED' via MCP call


async def run_analysis_pipeline(post_node_id: str, post_payload: Dict):
    """
    Fetches context via MCP, runs all analysis modules using LLM Interface,
    makes a decision, updates MCP, and triggers distribution if needed.
    """
    global llm_interface, fact_checker, contradiction_detector, evasion_detector, \
           disinformation_analyzer, decision_engine

    if not ANALYSIS_LOADED:
        logger.error(f"Analysis modules not loaded, cannot run pipeline for post node {post_node_id}.")
        return

    logger.info(f"Starting analysis pipeline for post node: {post_node_id}")
    analysis_results = {} # Store results from each module

    # Ensure required components are initialized
    if not all([llm_interface, decision_engine]):
        logger.error(f"Cannot run analysis pipeline for {post_node_id}: Core components (LLM Interface, Decision Engine) not initialized.")
        return

    # --- Fetch Context (Example: fetch related statements/votes via MCP) ---
    candidate_id = post_payload.get('candidate_id')
    context_statements = []
    context_votes = []
    if candidate_id:
        logger.debug(f"Fetching context for candidate {candidate_id} via MCP...")
        # Use await with the async helper function
        stmt_resp = await call_mcp_api('GET', f"/context/statements/{candidate_id}", params={'limit': 10})
        if stmt_resp and stmt_resp.get("status") == "success": context_statements = stmt_resp.get('statements', [])
        else: logger.warning(f"Failed to fetch statements context for {candidate_id}: {stmt_resp.get('error') if stmt_resp else 'No response'}")

        vote_resp = await call_mcp_api('GET', f"/context/votes/{candidate_id}", params={'limit': 20})
        if vote_resp and vote_resp.get("status") == "success": context_votes = vote_resp.get('votes', [])
        else: logger.warning(f"Failed to fetch votes context for {candidate_id}: {vote_resp.get('error') if vote_resp else 'No response'}")

        logger.debug(f"Fetched context: {len(context_statements)} statements, {len(context_votes)} votes.")
    else:
         logger.warning(f"Cannot fetch context for post {post_node_id}: candidate_id missing in payload.")

    # --- Run Analysis Modules (using LLM Interface) ---
    # Each analyzer uses the LLM interface internally. Assume they have async methods.
    try:
        tasks = []
        if contradiction_detector:
            tasks.append(contradiction_detector.analyze_new_post_contradictions_llm(
                candidate_id=candidate_id, new_post_content=post_payload.get('content',''),
                historical_statements=context_statements, historical_votes=context_votes
            ))
        else: tasks.append(asyncio.sleep(0, result={'contradiction_score': 0.0})) # Placeholder if disabled

        if evasion_detector:
            tasks.append(evasion_detector.analyze_evasiveness_llm(
                text_content=post_payload.get('content','')
            ))
        else: tasks.append(asyncio.sleep(0, result={'evasion_score': 0.0}))

        if fact_checker:
            tasks.append(fact_checker.check_statement_llm(
                text_content=post_payload.get('content','')
            ))
        else: tasks.append(asyncio.sleep(0, result={'fact_check_rating': 'Not Checked'}))

        if disinformation_analyzer:
            tasks.append(disinformation_analyzer.analyze_post_llm(
                post_data=post_payload, context_statements=context_statements
            ))
        else: tasks.append(asyncio.sleep(0, result={'disinfo_score': 0.0}))

        # Run analysis tasks concurrently
        logger.info(f"Running {len(tasks)} analysis modules concurrently for post {post_node_id}...")
        results = await asyncio.gather(*tasks, return_exceptions=True)
        logger.info(f"Completed analysis modules for post node: {post_node_id}")

        # Process results, handling potential exceptions from gather
        analysis_results['contradiction'] = results[0] if not isinstance(results[0], Exception) else {"error": str(results[0])}
        analysis_results['evasion'] = results[1] if not isinstance(results[1], Exception) else {"error": str(results[1])}
        analysis_results['fact_check'] = results[2] if not isinstance(results[2], Exception) else {"error": str(results[2])}
        analysis_results['disinformation'] = results[3] if not isinstance(results[3], Exception) else {"error": str(results[3])}

        # Log any errors from individual analyzers
        for key, res in analysis_results.items():
            if isinstance(res, dict) and res.get("error"):
                 logger.error(f"Error in {key} analysis for post {post_node_id}: {res['error']}")
            elif isinstance(res, Exception): # Handle exceptions returned by gather
                 logger.error(f"Exception in {key} analysis task for post {post_node_id}: {res}", exc_info=res)
                 analysis_results[key] = {"error": f"Task execution failed: {res}"} # Standardize error format

        logger.debug(f"Aggregated analysis results for {post_node_id}: {analysis_results}")

        # --- Make Decision ---
        # Decision engine combines results and updates MCP (synchronous call for now)
        decision_outcome = decision_engine.make_decision(
            post_node_id=post_node_id,
            post_data=post_payload, # Pass original post data for distribution context
            analysis_results=analysis_results # Pass aggregated results
        )
        logger.info(f"Decision made for post node {post_node_id}: {decision_outcome.get('decision')}")

        # Distribution is triggered *within* make_decision if thresholds met

    except Exception as e:
        logger.error(f"Critical error during analysis pipeline execution for post node {post_node_id}: {e}", exc_info=True)
        # Optionally update post status in DB to 'ANALYSIS_FAILED' via MCP call


# --- Lifespan Management ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    global mcp_session, llm_interface, report_generator, fact_checker, \
           contradiction_detector, evasion_detector, disinformation_analyzer, decision_engine
    logger.info("A2A Host application startup...")
    try:
        # Initialize MCP Session
        mcp_session = requests.Session()
        if INTERNAL_SERVICE_API_KEY:
            mcp_session.headers.update({"X-API-KEY": INTERNAL_SERVICE_API_KEY, "Accept": "application/json"})
            logger.info("A2A Host: MCP client session initialized with API Key.")
        else:
            logger.warning("A2A Host: Running without internal API key. MCP calls might fail auth.")

        # Initialize LLM Interface (reads keys from config)
        if ANALYSIS_LOADED:
            llm_interface = LLMInterface()

            # Initialize analysis engines (passing LLM interface)
            fact_checker = FactChecker(llm_interface=llm_interface)
            contradiction_detector = ContradictionDetector(llm_interface=llm_interface)
            evasion_detector = EvasionDetector(llm_interface=llm_interface)
            disinformation_analyzer = DisinformationAnalyzer(llm_interface=llm_interface)
            decision_engine = DecisionEngine() # Uses global mcp_session via helper
            report_generator = ReportGenerator() # Uses global mcp_session via helper
            logger.info("LLM Interface and analysis engines initialized.")
        else:
            logger.error("Analysis modules failed to load. Analysis features will be unavailable.")


    except Exception as e:
        logger.critical(f"CRITICAL ERROR during A2A Host startup: {e}", exc_info=True)
        # Prevent startup if critical components fail
        raise RuntimeError("Failed to initialize critical A2A Host components") from e
    yield
    # Shutdown
    logger.info("A2A Host application shutdown...")
    if mcp_session:
        mcp_session.close()
        logger.info("MCP session closed.")
    # Add any other cleanup needed (e.g., close LLM clients if necessary)
    logger.info("A2A Host resources cleaned up.")

# --- FastAPI App Creation ---
app = FastAPI(
    title="Oppo A2A Host",
    description="Provides opposition research data and analysis via A2A protocols, including real-time social media ingestion and LLM analysis.",
    version="0.1.0-llm",
    lifespan=lifespan # Register lifespan context manager
)

# --- CORS Middleware ---
# Configure allowed origins based on environment (more restrictive in production)
allow_origins_env = os.getenv("ALLOWED_ORIGINS", "http://localhost:8080,http://127.0.0.1:8080")
origins = [origin.strip() for origin in allow_origins_env.split(",")] if allow_origins_env else ["http://localhost:8080"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins, # Use configured origins
    allow_credentials=True, # Allow cookies if needed for frontend auth
    allow_methods=["*"], # Allow all standard methods
    allow_headers=["*"], # Allow all standard headers
)


# --- API Routers ---
# Token endpoint for user login
@app.post("/token", response_model=Token, tags=["Authentication"])
async def login_for_access_token_route(form_data: OAuth2PasswordRequestForm = Depends()):
    user = authenticate_user(form_data.username, form_data.password)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    access_token = create_access_token(data={"sub": user.username})
    return {"access_token": access_token, "token_type": "bearer"}

# Main API router for external A2A agents (/opposition/*)
app.include_router(main_api_router)


# --- Internal Ingestion Endpoint ---
# Secured with internal API key
@app.post(
    "/ingest/social_post",
    tags=["Internal Ingestion"],
    summary="Endpoint for listeners to submit new social posts",
    dependencies=[Depends(verify_internal_api_key)] # Secure this endpoint!
)
async def ingest_social_post_route(
    background_tasks: BackgroundTasks,
    post_payload: Dict[str, Any] = Body(...) # Receive raw dict from listener
    ):
    """
    Receives social post data from internal listeners, requests storage via MCP,
    and triggers the analysis pipeline as a background task.
    """
    global mcp_session # Use the global session for MCP calls

    # Validate payload structure roughly before proceeding
    if not isinstance(post_payload, dict) or not post_payload.get('candidate_id') or not post_payload.get('post_id'):
         logger.error(f"Received invalid ingestion payload structure: {str(post_payload)[:500]}")
         raise HTTPException(status_code=422, detail="Invalid post data format received.")

    # Validate using Pydantic model if loaded
    if MODELS_LOADED:
        try:
            # This ensures basic structure and types match SocialPost expectations
            # Note: This uses the *full* SocialPost model, including analysis fields which will be None initially.
            # Consider a separate IngestionPost model if needed.
            _ = SocialPost(**post_payload)
        except ValidationError as e:
            logger.error(f"Ingestion payload failed Pydantic validation: {e}")
            raise HTTPException(status_code=422, detail=f"Invalid post data: {e}")

    logger.info(f"Received ingestion request: Platform={post_payload.get('source_platform')}, ID={post_payload.get('post_id')}, Cand={post_payload.get('candidate_id')}")

    # 1. Request MCP Server to store the post
    # Use await for the async helper
    mcp_response = await call_mcp_api('POST', '/social_post', json_payload=post_payload)

    if not mcp_response or mcp_response.get('error'):
        error_detail = mcp_response.get('error', 'Unknown error storing post via MCP') if mcp_response else 'No response from MCP'
        logger.error(f"Failed to store social post via MCP: {error_detail}")
        # Decide if we should still trigger analysis? Probably not if storage failed.
        raise HTTPException(status_code=502, detail=f"Failed to store social post: {error_detail}") # 502 Bad Gateway

    post_node_id = mcp_response.get('post_node_id')
    if not post_node_id:
        logger.error(f"MCP Server stored post but did not return node ID. Payload: {post_payload}")
        # Cannot trigger analysis without node ID
        raise HTTPException(status_code=500, detail="Internal error: Failed to get post node ID after storage.")

    logger.info(f"Post stored via MCP, node ID: {post_node_id}. Triggering background analysis.")

    # 2. Trigger Analysis Pipeline as Background Task
    # Pass the node ID and the original payload (contains content etc.)
    background_tasks.add_task(trigger_analysis_task, post_node_id, post_payload)

    return {"message": "Social post ingested and analysis triggered successfully", "post_node_id": post_node_id}


# --- Root Endpoint ---
@app.get("/", tags=["Root"], summary="Root endpoint for API status")
async def root():
    """Provides basic status information about the A2A Host."""
    return {"message": "Oppo A2A Host v0.1 (LLM-Powered) - Ready"}

# --- Health Check Endpoint ---
@app.get("/health", tags=["Health Check"], summary="Check service health")
async def health_check():
    """Performs basic health checks on the service and dependencies."""
    # Check MCP connection (simple GET request to MCP root)
    mcp_status = "unknown"
    if mcp_session and MCP_SERVER_URL:
        try:
            # Use await for the async helper
            mcp_response = await call_mcp_api('GET', '/')
            if mcp_response and not mcp_response.get('error'):
                mcp_status = "ok"
            else:
                mcp_status = f"error: {mcp_response.get('error', 'MCP connection failed')}"
        except Exception as e:
            mcp_status = f"error: {str(e)[:100]}"
    else:
        mcp_status = "not configured"

    # Check if LLM interface seems configured
    llm_status = "ok" if llm_interface and llm_interface.providers else "not configured/failed init"

    # Determine overall status
    overall_ok = mcp_status == "ok" and llm_status == "ok"

    return {
        "status": "ok" if overall_ok else "error",
        "version": "0.1.0-llm",
        "dependencies": {
            "mcp_server": mcp_status,
            "llm_interface": llm_status,
        },
        "analysis_components_loaded": {
            "llm_interface": bool(llm_interface),
            "fact_checker": bool(fact_checker),
            "contradiction_detector": bool(contradiction_detector),
            "evasion_detector": bool(evasion_detector),
            "disinformation_analyzer": bool(disinformation_analyzer),
            "decision_engine": bool(decision_engine),
            "report_generator": bool(report_generator)
        }
    }