# -*- coding: utf-8 -*-
"""disinformation_analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFaEJo9GCQswpN47HmnzkKKUuR8icMVq
"""

# File: Oppo/analysis/disinformation_analyzer.py
# Purpose: Uses LLM to analyze posts for disinformation markers.

import logging
import os
import json
import asyncio
from typing import Dict, List, Any, Optional

# Import LLM Interface and models
from .llm_interface import LLMInterface, LlmProvider
try:
    from database.data_models import Statement, SocialPost # For type hinting context/post
    MODELS_LOADED = True
except ImportError:
     logging.error("Could not import data models for DisinformationAnalyzer.")
     MODELS_LOADED = False
     class Statement: pass
     class SocialPost: pass


# Import config for LLM provider selection
try:
    from a2a_host.config import DISINFO_LLM_PROVIDER, LOG_LEVEL
    CONFIG_LOADED = True
except ImportError:
     log_level_env = os.getenv("LOG_LEVEL", "INFO").upper()
     logging.basicConfig(level=getattr(logging, log_level_env, logging.INFO), format='%(asctime)s:%(levelname)s:%(name)s:%(lineno)d:%(message)s')
     logger = logging.getLogger(__name__)
     logger.warning("Could not import config from a2a_host for DisinformationAnalyzer. Using environment variables.")
     DISINFO_LLM_PROVIDER = os.getenv("DISINFO_LLM_PROVIDER", "GEMINI") # Default to Gemini
     LOG_LEVEL = log_level_env
     CONFIG_LOADED = True

# Ensure logging is configured
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format='%(asctime)s:%(levelname)s:%(name)s:%(lineno)d:%(message)s',
    force=True
)
logger = logging.getLogger(__name__)

# --- Constants ---
DEFAULT_PROVIDER: LlmProvider = DISINFO_LLM_PROVIDER or "GEMINI" # Fallback provider

# --- Prompts (Customize these extensively based on desired analysis) ---
# Consider adding specific known narratives, source checking instructions, etc.
DISINFO_SYSTEM_PROMPT = """
You are an AI assistant specialized in identifying potential disinformation and problematic content in political communication.
Analyze the provided 'New Statement/Post'. Consider its content, tone, and any provided context.
Identify potential markers of disinformation, such as:
- Use of known propaganda techniques (e.g., whataboutism, false dichotomy, ad hominem, appeal to emotion over reason).
- Alignment with known harmful narratives or conspiracy theories.
- Presence of unsubstantiated claims or lack of credible sourcing (if source info is available).
- Use of inflammatory, highly biased, or emotionally manipulative language.
- Potential presence of AI-generated or manipulated media indicators (based on text description if applicable).

Provide your analysis in JSON format with the following keys:
- "disinfo_score": float (Estimate the likelihood this post contains disinformation or highly problematic content, 0.0 to 1.0. Higher means more likely).
- "disinfo_flags": list[string] (List of specific flags identified, e.g., ["PROPAGANDA_TECHNIQUE:Whataboutism", "KNOWN_NARRATIVE:Election Fraud", "INFLAMMATORY_LANGUAGE", "UNSUBSTANTIATED_CLAIM"]). Be specific. If none, return empty list [].
- "explanation": string (Briefly justify the score and flags, explaining the reasoning.)
"""

DISINFO_USER_PROMPT_TEMPLATE = """
**Candidate Context:** (Assume statements/posts are from the same candidate unless specified)
* Recent Statements: {statements_context}

**New Statement/Post:**
* Platform: {platform}
* Author: {author}
* Timestamp: {timestamp}
* URL: {url}
* Content:
{new_post_content}

**Analysis Task:** Based ONLY on the provided information, analyze the 'New Statement/Post' for potential disinformation markers as described in the system prompt. Provide your analysis in the specified JSON format. Focus only on the new post, using context for background if relevant.
"""

class DisinformationAnalyzer:
    """
    Uses an LLM via the LLMInterface to analyze posts for markers of
    disinformation or problematic content.
    """
    def __init__(self, llm_interface: LLMInterface):
        """
        Initializes the DisinformationAnalyzer.
        Args:
            llm_interface: An instance of the LLMInterface.
        """
        if not isinstance(llm_interface, LLMInterface):
             raise TypeError("llm_interface must be an instance of LLMInterface")
        self.llm = llm_interface
        # Determine the provider from config
        self.provider: LlmProvider = DEFAULT_PROVIDER
        if DISINFO_LLM_PROVIDER not in self.llm.providers:
             logger.warning(f"Configured disinformation provider '{DISINFO_LLM_PROVIDER}' not available. Falling back.")
             available_providers = list(self.llm.providers.keys())
             if DEFAULT_PROVIDER in available_providers: self.provider = DEFAULT_PROVIDER
             elif available_providers: self.provider = available_providers[0]
             else: raise RuntimeError("No configured LLM provider available for disinformation analysis.")
        logger.info(f"DisinformationAnalyzer initialized using LLM provider: {self.provider}")

    def _format_context_for_prompt(self, context_statements: List[Dict], max_items: int = 3) -> str:
        """Formats context statements for the prompt."""
        if not context_statements: return "No recent statements provided."
        formatted = []
        for stmt in context_statements[:max_items]:
             date_str = stmt.get('date', '?')
             text_snippet = (stmt.get('text', '') or '')[:150] + "..."
             formatted.append(f"- ({date_str}): {text_snippet}")
        return "\n".join(formatted)


    async def analyze_post_llm(
        self,
        post_data: Dict[str, Any], # Expects a dict similar to SocialPost model
        context_statements: List[Dict] # Historical statements from MCP
    ) -> Dict[str, Any]:
        """
        Analyzes a post for disinformation markers using an LLM.

        Args:
            post_data: Dictionary containing the post details.
            context_statements: List of historical statement dicts for context.

        Returns:
            Dict: {'disinfo_score': float, 'disinfo_flags': list, 'explanation': str, 'error': str|None}
        """
        post_id = post_data.get('post_id', 'Unknown ID')
        logger.info(f"Running LLM disinformation check for post: {post_id}")
        default_response = {'disinfo_score': 0.0, 'disinfo_flags': [], 'explanation': 'Analysis could not be performed.', 'error': 'LLM analysis skipped or failed.'}

        content = post_data.get('content')
        if not content:
            logger.warning(f"Cannot check disinformation: Post content is empty for post {post_id}.")
            default_response['explanation'] = "No content provided in the post."
            default_response['error'] = "Missing content"
            return default_response

        if not self.llm or not self.provider:
             logger.error("LLM Interface or provider not available for disinformation check.")
             return default_response

        # Format context
        statements_context_str = self._format_context_for_prompt(context_statements)

        # Construct the prompt
        prompt = DISINFO_USER_PROMPT_TEMPLATE.format(
            statements_context=statements_context_str,
            platform=post_data.get('source_platform', 'N/A'),
            author=post_data.get('author_username', 'N/A'),
            timestamp=post_data.get('timestamp', 'N/A'),
            url=post_data.get('url', 'N/A'),
            new_post_content=content
        )

        llm_kwargs = {}
        if self.provider == "ANTHROPIC":
             llm_kwargs["system_prompt"] = DISINFO_SYSTEM_PROMPT

        # Call LLM, requesting JSON
        llm_response = await self.llm.call_llm_async(
            prompt=prompt if self.provider != "ANTHROPIC" else DISINFO_USER_PROMPT_TEMPLATE,
            provider=self.provider,
            json_output=True,
            **llm_kwargs
        )

        # Parse the LLM response
        if llm_response['status'] == 'success' and isinstance(llm_response['result'], dict):
            result_json = llm_response['result']
            logger.debug(f"LLM Disinformation JSON result: {result_json}")
            # Validate expected keys and types
            disinfo_score = result_json.get('disinfo_score', 0.0)
            flags = result_json.get('disinfo_flags', [])
            explanation = result_json.get('explanation', 'No explanation provided.')

            try:
                score = float(disinfo_score)
                if not (0.0 <= score <= 1.0): score = 0.0 # Clamp
            except (ValueError, TypeError):
                 logger.warning(f"LLM returned invalid disinfo_score: {disinfo_score}. Defaulting to 0.")
                 score = 0.0

            if not isinstance(flags, list):
                 logger.warning(f"LLM returned invalid type for disinfo_flags: {type(flags)}. Defaulting to empty list.")
                 flags = []

            return {
                'disinfo_score': round(score, 3),
                'disinfo_flags': [str(f) for f in flags if isinstance(f, (str, int, float))], # Ensure flags are strings
                'explanation': explanation,
                'error': None
            }
        elif llm_response['status'] == 'success' and isinstance(llm_response['result'], str):
             logger.warning(f"LLM disinfo check returned string instead of JSON: {llm_response['result'][:200]}...")
             # Attempt simple parse or return default error
             # This part could be improved with regex or more robust parsing attempts
             score = 0.5 # Assign arbitrary score on format failure
             explanation = "LLM analysis failed to return valid JSON structure."
             flags = ["LLM_FORMAT_ERROR"]
             return {'disinfo_score': score, 'disinfo_flags': flags, 'explanation': explanation, 'error': "LLM JSON format error"}
        else:
            # Handle API errors or blocked content
            logger.error(f"LLM disinformation check failed for post {post_id}. Error: {llm_response.get('error')}")
            default_response['error'] = llm_response.get('error', 'Unknown LLM API error')
            if llm_response.get('blocked'):
                 default_response['explanation'] = f"Analysis blocked by content safety filter: {llm_response.get('block_reason')}"
            return default_response