# -*- coding: utf-8 -*-
"""llm_interface

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKRYdNRDdzCivG8a4Jde4l4M4jm2znr9
"""

# File: Oppo/analysis/llm_interface.py
# Purpose: Provides a unified interface to interact with different configured LLM APIs.

import logging
import os
import time
import json
from typing import Dict, Any, Optional, Literal, Tuple

# Import config from a2a_host
try:
    from a2a_host.config import (
        GOOGLE_API_KEY,
        OPENAI_API_KEY,       # Load key even if provider not default
        ANTHROPIC_API_KEY,    # Load key even if provider not default
        GEMINI_MODEL_NAME,
        OPENAI_MODEL_NAME,    # Load default model name
        ANTHROPIC_MODEL_NAME, # Load default model name
        LOG_LEVEL
    )
    CONFIG_LOADED = True
except ImportError as e:
    # Fallback logging setup if config import fails
    log_level_env = os.getenv("LOG_LEVEL", "INFO").upper()
    logging.basicConfig(level=getattr(logging, log_level_env, logging.INFO), format='%(asctime)s:%(levelname)s:%(name)s:%(lineno)d:%(message)s')
    logger = logging.getLogger(__name__)
    logger.warning(f"Could not import config from a2a_host ({e}). Loading LLM keys/models from environment.")
    GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
    GEMINI_MODEL_NAME = os.getenv("GEMINI_MODEL_NAME", "gemini-1.5-flash-latest") # Default model
    OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME", "gpt-4o")
    ANTHROPIC_MODEL_NAME = os.getenv("ANTHROPIC_MODEL_NAME", "claude-3-haiku-20240307")
    LOG_LEVEL = log_level_env
    CONFIG_LOADED = True # Assume loaded from env

# LLM SDK Imports (Add more as needed)
try:
    import google.generativeai as genai
    from google.generativeai.types import HarmCategory, HarmBlockThreshold
    GOOGLE_AI_LOADED = True
except ImportError:
    logging.warning("google-generativeai SDK not found. Gemini provider disabled. Install with: pip install google-generativeai")
    GOOGLE_AI_LOADED = False
    genai = None
    # Define dummy types if needed for type hints below
    class HarmCategory: pass
    class HarmBlockThreshold: pass


try:
    import openai
    OPENAI_LOADED = True
except ImportError:
    logging.warning("openai SDK not found. OpenAI provider disabled. Install with: pip install openai")
    OPENAI_LOADED = False
    openai = None

try:
    import anthropic
    ANTHROPIC_LOADED = True
except ImportError:
    logging.warning("anthropic SDK not found. Anthropic provider disabled. Install with: pip install anthropic")
    ANTHROPIC_LOADED = False
    anthropic = None


# Configure logging (ensure it's configured based on loaded LOG_LEVEL)
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format='%(asctime)s:%(levelname)s:%(name)s:%(lineno)d:%(message)s',
    force=True # Reconfigure if needed
)
logger = logging.getLogger(__name__)
# Quieten SDK loggers if desired
logging.getLogger("google.generativeai").setLevel(logging.WARNING)
logging.getLogger("openai").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING) # Used by openai/anthropic


# Supported LLM Providers (extend this type as needed)
LlmProvider = Literal["GEMINI", "OPENAI", "ANTHROPIC"]

# Default safety settings for Gemini (can be overridden via kwargs)
DEFAULT_GEMINI_SAFETY_SETTINGS = {
    HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
} if GOOGLE_AI_LOADED else {}

class LLMInterface:
    """
    Handles communication with configured Large Language Models.
    Provides an abstraction layer over different LLM provider APIs.
    """
    def __init__(self):
        """Initializes the LLM Interface, configuring available providers."""
        self.providers: Dict[LlmProvider, Any] = {}
        self.default_models: Dict[LlmProvider, Optional[str]] = {}

        # Configure Google Gemini (if available and key provided)
        if GOOGLE_AI_LOADED and GOOGLE_API_KEY:
            try:
                genai.configure(api_key=GOOGLE_API_KEY)
                # Test configuration by listing models (optional, adds startup time/call)
                # models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
                # logger.debug(f"Available Gemini models: {models}")
                self.providers["GEMINI"] = genai # Store the configured module
                self.default_models["GEMINI"] = GEMINI_MODEL_NAME
                logger.info(f"LLMInterface: Configured GEMINI provider with default model '{GEMINI_MODEL_NAME}'.")
            except Exception as e:
                 logger.error(f"LLMInterface: Failed to configure GEMINI provider: {e}", exc_info=True)
        else:
             logger.warning("LLMInterface: GEMINI provider not configured (SDK loaded: %s, API Key set: %s)",
                          GOOGLE_AI_LOADED, bool(GOOGLE_API_KEY))

        # Configure OpenAI (if available and key provided)
        if OPENAI_LOADED and OPENAI_API_KEY:
            try:
                self.providers["OPENAI"] = openai.OpenAI(api_key=OPENAI_API_KEY) # Instantiate client
                self.default_models["OPENAI"] = OPENAI_MODEL_NAME
                # Test connection? e.g., self.providers["OPENAI"].models.list()
                logger.info(f"LLMInterface: Configured OPENAI provider with default model '{OPENAI_MODEL_NAME}'.")
            except Exception as e:
                 logger.error(f"LLMInterface: Failed to configure OPENAI provider: {e}", exc_info=True)
        else:
             logger.warning("LLMInterface: OPENAI provider not configured (SDK loaded: %s, API Key set: %s)",
                          OPENAI_LOADED, bool(OPENAI_API_KEY))

        # Configure Anthropic (if available and key provided)
        if ANTHROPIC_LOADED and ANTHROPIC_API_KEY:
            try:
                self.providers["ANTHROPIC"] = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY) # Instantiate client
                self.default_models["ANTHROPIC"] = ANTHROPIC_MODEL_NAME
                # Test connection? e.g., self.providers["ANTHROPIC"].count_tokens("test", model=ANTHROPIC_MODEL_NAME)
                logger.info(f"LLMInterface: Configured ANTHROPIC provider with default model '{ANTHROPIC_MODEL_NAME}'.")
            except Exception as e:
                 logger.error(f"LLMInterface: Failed to configure ANTHROPIC provider: {e}", exc_info=True)
        else:
             logger.warning("LLMInterface: ANTHROPIC provider not configured (SDK loaded: %s, API Key set: %s)",
                          ANTHROPIC_LOADED, bool(ANTHROPIC_API_KEY))

        if not self.providers:
            logger.error("LLMInterface: No LLM providers could be configured. Analysis using LLMs will fail.")

    def _is_retryable_error(self, provider: LlmProvider, error: Exception) -> bool:
        """Checks if an error from a specific provider is likely retryable."""
        # Generic network errors
        if isinstance(error, (requests.exceptions.Timeout, requests.exceptions.ConnectionError)):
             return True

        # Provider-specific errors (add more as needed based on SDKs)
        if provider == "GEMINI":
            # Google API errors often have response attributes
            if hasattr(error, 'response') and hasattr(error.response, 'status_code'):
                 return error.response.status_code in [429, 500, 503] # Rate limit, server error
            # Check for specific Google API error types if the SDK raises them
            # from google.api_core import exceptions as google_exceptions
            # if isinstance(error, (google_exceptions.RetryError, google_exceptions.ServiceUnavailable, google_exceptions.ResourceExhausted)):
            #     return True
        elif provider == "OPENAI":
            if openai and isinstance(error, (openai.RateLimitError, openai.APIConnectionError, openai.InternalServerError)):
                 return True
        elif provider == "ANTHROPIC":
             if anthropic and isinstance(error, (anthropic.RateLimitError, anthropic.APIConnectionError, anthropic.InternalServerError)):
                  return True

        return False

    async def call_llm_async(self,
                       prompt: str,
                       provider: LlmProvider,
                       model_name: Optional[str] = None,
                       max_retries: int = 2,
                       initial_delay: float = 1.5,
                       **kwargs # Pass additional args to underlying SDK (e.g., temperature, max_tokens)
                       ) -> Dict[str, Any]:
        """
        Asynchronously calls the specified LLM provider with the given prompt.

        Args:
            prompt: The input prompt for the LLM.
            provider: The LLM provider to use ("GEMINI", "OPENAI", "ANTHROPIC").
            model_name: The specific model to use (optional, defaults to configured default).
            max_retries: Maximum number of retries on transient errors.
            initial_delay: Initial delay (in seconds) before the first retry.
            **kwargs: Additional keyword arguments for the LLM API call (e.g., temperature).

        Returns:
            A dictionary containing:
                {'status': 'success', 'result': str, 'error': None} on success.
                {'status': 'error', 'result': None, 'error': str} on failure.
        """
        if provider not in self.providers:
            logger.error(f"LLM provider '{provider}' not available or configured.")
            return {'status': 'error', 'result': None, 'error': f"Provider '{provider}' not configured"}

        selected_model = model_name or self.default_models.get(provider)
        if not selected_model:
            logger.error(f"No model specified and no default model configured for provider '{provider}'.")
            return {'status': 'error', 'result': None, 'error': f"No model configured for '{provider}'"}

        logger.info(f"Async Call to LLM Provider: {provider}, Model: {selected_model}")
        logger.debug(f"LLM Prompt (first 100 chars): {prompt[:100]}...")

        result_text = None
        error_message = None
        retries = 0
        current_delay = initial_delay

        while retries <= max_retries:
            try:
                if provider == "GEMINI":
                    client_module: Optional[genai] = self.providers.get("GEMINI")
                    if not client_module: raise RuntimeError("Gemini client module not initialized")

                    safety_settings = kwargs.get("safety_settings", DEFAULT_GEMINI_SAFETY_SETTINGS)
                    generation_config_dict = {
                        "temperature": kwargs.get('temperature', 0.7),
                        "max_output_tokens": kwargs.get('max_tokens', 2048), # Default max tokens
                        # Add other Gemini generation config params from kwargs if needed
                    }
                    # Filter out None values from config dict
                    generation_config_dict = {k: v for k, v in generation_config_dict.items() if v is not None}
                    generation_config = genai.types.GenerationConfig(**generation_config_dict)

                    model_instance = client_module.GenerativeModel(selected_model)

                    # Use generate_content_async for asynchronous call
                    response = await model_instance.generate_content_async(
                        prompt,
                        generation_config=generation_config,
                        safety_settings=safety_settings
                    )

                    # Handle potential content filtering/blocking
                    if not response.candidates:
                         block_reason = response.prompt_feedback.block_reason if response.prompt_feedback else 'Unknown'
                         safety_ratings = response.prompt_feedback.safety_ratings if response.prompt_feedback else []
                         logger.warning(f"Gemini response blocked. Reason: {block_reason}. Ratings: {safety_ratings}")
                         error_message = f"Content blocked by API. Reason: {block_reason}"
                         return {'status': 'error', 'result': None, 'error': error_message, 'blocked': True, 'block_reason': str(block_reason)}

                    result_text = response.text

                # --- Add Async OpenAI Logic ---
                elif provider == "OPENAI":
                    client: Optional[openai.AsyncOpenAI] = self.providers.get("OPENAI") # Assume async client stored
                    if not client: raise RuntimeError("Async OpenAI client not initialized")
                    # Ensure using async client's method
                    response = await client.chat.completions.create(
                        model=selected_model,
                        messages=[{"role": "user", "content": prompt}],
                        temperature=kwargs.get('temperature', 0.7),
                        max_tokens=kwargs.get('max_tokens', 2048),
                    )
                    if response.choices:
                         result_text = response.choices[0].message.content
                    else:
                         logger.warning("OpenAI response had no choices.")
                         error_message = "OpenAI response missing choices." # Treat as error

                # --- Add Async Anthropic Logic ---
                elif provider == "ANTHROPIC":
                    client: Optional[anthropic.AsyncAnthropic] = self.providers.get("ANTHROPIC") # Assume async client stored
                    if not client: raise RuntimeError("Async Anthropic client not initialized")
                    response = await client.messages.create(
                        model=selected_model,
                        max_tokens=kwargs.get('max_tokens', 2048),
                        temperature=kwargs.get('temperature', 0.7),
                        messages=[{"role": "user", "content": prompt}]
                    )
                    if response.content and isinstance(response.content, list) and hasattr(response.content[0], 'text'):
                         result_text = response.content[0].text
                    else:
                         logger.warning(f"Unexpected Anthropic response structure: {response}")
                         error_message = "Anthropic response structure unexpected."

                # --- If successful ---
                if result_text is not None:
                    logger.info(f"Async LLM call successful ({provider}/{selected_model}).")
                    logger.debug(f"LLM Result (first 100 chars): {result_text[:100]}...")
                    return {'status': 'success', 'result': result_text.strip(), 'error': None}
                else:
                    error_message = error_message or "LLM call succeeded but no result text extracted."
                    logger.error(error_message)
                    return {'status': 'error', 'result': None, 'error': error_message}

            # --- Error Handling & Retries ---
            except Exception as e:
                error_message = f"Error calling {provider} API: {str(e)}"
                logger.error(f"{error_message} (Attempt {retries + 1}/{max_retries + 1})", exc_info=False)

                if self._is_retryable_error(provider, e) and retries < max_retries:
                    retries += 1
                    logger.warning(f"Retryable error encountered. Retrying in {current_delay:.1f} seconds...")
                    await asyncio.sleep(current_delay)
                    current_delay *= 2 # Exponential backoff
                    continue # Retry the loop
                else:
                    # Non-retryable error or max retries exceeded
                    logger.error(f"Async LLM call failed after {retries} retries for {provider}/{selected_model}.")
                    logger.debug("LLM Error Details:", exc_info=True)
                    # Extract more specific error message if possible
                    # (Provider specific error parsing might be needed here too)
                    return {'status': 'error', 'result': None, 'error': error_message}

        # Fallback if loop finishes unexpectedly
        return {'status': 'error', 'result': None, 'error': error_message or "Max retries exceeded"}